### PR TITLE
fix(cli): project delete empty s3 buckets before deleting

### LINKED ISSUE #700: Update project delete to empty s3 buckets before deleting
Currently `project delete` will fail if users deployed a pipeline (basically because the s3 bucket will not be empty and throw an error when trying to delete them). We should clear all objects in s3 buckets before we try to delete them.

### PR DESCRIPTION
**Pull request by iamhopaul123**
fix #700, with minor refactoring.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: internal/pkg/aws/s3/s3.go [hunk 1]
```diff
@@ -52,3 +61,64 @@ func (s *Service) PutArtifact(bucket, fileName string, data io.Reader) (string,
 
 	return resp.Location, nil
 }
+
+// EmptyBucket deletes all objects within the bucket.
+func (s *Service) EmptyBucket(bucket string) error {
```
Comment (efekarakus) [inline internal/pkg/aws/s3/s3.go]: Check this out! https://github.com/awsdocs/aws-doc-sdk-examples/blob/bc948130e67d8f9a3adb8c1980ddf5405aed4e33/go/example_code/s3/s3_delete_objects.go#L62-L69

I think using the `BatchDeleteIterator` can make our lives a lot easier :), let me know if I'm missing something

File: internal/pkg/cli/project_delete.go [hunk 2]
```diff
@@ -38,10 +39,13 @@ type deleteProjVars struct {
...
 type deleteProjOpts struct {
 	deleteProjVars
-	store    projectService
-	deployer deployer
-	ws       workspaceDeleter
-	spinner  progress
+	store               projectService
+	deployer            deployer
+	projResourcesGetter projectResourcesGetter
+	bucketEmptySvc      bucketEmptier
```
Comment (efekarakus) [inline internal/pkg/cli/project_delete.go]: nit:  
```suggestion
	s3Client      bucketEmptier
```

File: internal/pkg/cli/project_delete.go [hunk 3]
```diff
@@ -182,26 +212,58 @@ func (o *deleteProjOpts) deleteEnvs() error {
...
+	proj, err := o.store.GetProject(o.ProjectName())
+	if err != nil {
+		return fmt.Errorf("get project %s: %w", o.ProjectName(), err)
+	}
+	projResources, err := o.projResourcesGetter.GetRegionalProjectResources(proj)
 	if err != nil {
+		return fmt.Errorf("get regional resources for %s: %w", proj.Name, err)
+	}
+	for _, projResource := range projResources {
+		o.spinner.Start(fmt.Sprintf("Deleting S3 bucket objects in %s.", projResource.Region))
```
Comment (efekarakus) [inline internal/pkg/cli/project_delete.go]: can we add the name of the bucket? maybe something like
```suggestion
		o.spinner.Start(fmt.Sprintf("Emptying the pipeline bucket %s in %s.", color.HighlightResource(projResource.S3Bucket), projResource.Region))
```

File: internal/pkg/cli/project_delete.go [hunk 4]
```diff
@@ -182,26 +212,58 @@ func (o *deleteProjOpts) deleteEnvs() error {
...
+		o.initBucketEmptySvc(o, projResource.Region)
+		if err := o.bucketEmptySvc.EmptyBucket(projResource.S3Bucket); err != nil {
+			o.spinner.Stop(log.Serror("Error deleting S3 bucket objects."))
+			return fmt.Errorf("empty bucket %s: %w", projResource.S3Bucket, err)
+		}
+		o.spinner.Stop(log.Ssuccess(fmt.Sprintf("Deleted S3 bucket objects in %s.", projResource.Region)))
```
Comment (efekarakus) [inline internal/pkg/cli/project_delete.go]: samesies here

File: internal/pkg/cli/project_delete.go [hunk 5]
```diff
@@ -182,26 +212,58 @@ func (o *deleteProjOpts) deleteEnvs() error {
...
+		o.spinner.Stop(log.Serror("Error deleting project resources."))
+		return fmt.Errorf("delete project resources: %w", err)
+	}
+	o.spinner.Stop(log.Ssuccess("Deleted project resources."))
+
+	return nil
+}
+
+func (o *deleteProjOpts) deleteProjectParams() error {
+	o.spinner.Start("Deleting project parameters.")
```
Comment (efekarakus) [inline internal/pkg/cli/project_delete.go]: nit:
```suggestion
	o.spinner.Start("Deleting project metadata.")
```

File: internal/pkg/aws/s3/s3.go (hunk 1 above)
Comment (iamhopaul123) [reply internal/pkg/aws/s3/s3.go]: Yeah, problem with this method is we are using versioning bucket so this cannot entirely empty the bucket. Instead this will create delete marker for each file for the next version. And the reason why we need to delete "delete marker" at the end of this function is to deal with the edge case where users might delete some of the files themselves so that "delete marker" will be created, which will not be deleted by the code snippet in the "for loop".

File: internal/pkg/cli/project_delete.go (hunk 3 above)
Comment (iamhopaul123) [reply internal/pkg/cli/project_delete.go]: Nice!

File: internal/pkg/aws/s3/s3.go [hunk 6]
```diff
@@ -13,26 +13,35 @@ import (
 
 	"github.com/aws/aws-sdk-go/aws"
 	"github.com/aws/aws-sdk-go/aws/session"
+	"github.com/aws/aws-sdk-go/service/s3"
 	"github.com/aws/aws-sdk-go/service/s3/s3manager"
 )
 
 const (
 	artifactDirName = "manual"
+	batchSize       = 1000
```
Comment (efekarakus) [inline internal/pkg/aws/s3/s3.go]: Do we need this? I think the SDK will automatically reply to us with 1000 items if there are at least that many objects.

File: internal/pkg/aws/s3/s3.go [hunk 7]
```diff
@@ -52,3 +61,64 @@ func (s *Service) PutArtifact(bucket, fileName string, data io.Reader) (string,
...
+	// Remove all versions of all objects.
+	for {
+		listResp, err = s.s3Svc.ListObjectVersions(listParams)
+		if err != nil {
+			return fmt.Errorf("list objects for bucket %s: %w", bucket, err)
+		}
+		if len(listResp.Versions) == 0 {
+			break
+		}
+		objectsID := make([]*s3.ObjectIdentifier, 0, batchSize)
```
Comment (efekarakus) [inline internal/pkg/aws/s3/s3.go]: can we remove `batchSize` and just say: `make([]*s3.ObjectIdentifier, 0, len(listResp.Versions))`

File: internal/pkg/aws/s3/s3.go [hunk 8]
```diff
@@ -52,3 +61,64 @@ func (s *Service) PutArtifact(bucket, fileName string, data io.Reader) (string,
...
+		if aws.BoolValue(listResp.IsTruncated) {
+			listParams.KeyMarker = listResp.NextKeyMarker
+			listParams.VersionIdMarker = listResp.NextVersionIdMarker
+		}
+	}
+	// After deleting all versions for all objects, remove all delete marker.
+	// For info on "delete marker": https://docs.aws.amazon.com/AmazonS3/latest/dev/DeleteMarker.html
+	if len(listResp.DeleteMarkers) == 0 {
+		return nil
+	}
```
Comment (efekarakus) [inline internal/pkg/aws/s3/s3.go]: dumb question: should we not collect all `DeleteMarkers` within the `for` loop above and not just at the end?

File: internal/pkg/aws/s3/s3.go [hunk 9]
```diff
@@ -52,3 +61,64 @@ func (s *Service) PutArtifact(bucket, fileName string, data io.Reader) (string,
...
+			Key:       deleteMarker.Key,
+			VersionId: deleteMarker.VersionId,
+		})
+	}
+	_, err = s.s3Svc.DeleteObjects(&s3.DeleteObjectsInput{
+		Bucket: aws.String(bucket),
+		Delete: &s3.Delete{
+			Objects: deleteMarkers,
+		},
+	})
```
Comment (efekarakus) [inline internal/pkg/aws/s3/s3.go]: Is it possible that we have more than 1000 deletemarkers and we need to split these up to multiple requests?

File: internal/pkg/aws/s3/s3.go (hunk 8 above)
Comment (iamhopaul123) [reply internal/pkg/aws/s3/s3.go]: Good question actually, I need to test it out. They don't have enough words on that in the doc. But I think we will have a lot duplication because "delete marker" won't change when we deleting the versions.

File: internal/pkg/aws/s3/s3.go (hunk 9 above)
Comment (iamhopaul123) [reply internal/pkg/aws/s3/s3.go]: Good questions! I am not sure either and they don't have a `nextdeletemarker` such kind of stuff, nor do they specify there could be some limitation for the length of "DeleteMarkers" field.

File: internal/pkg/aws/s3/s3.go [hunk 10]
```diff
@@ -52,3 +60,46 @@ func (s *Service) PutArtifact(bucket, fileName string, data io.Reader) (string,
 
 	return resp.Location, nil
 }
+
+// EmptyBucket deletes all objects within the bucket.
+func (s *Service) EmptyBucket(bucket string) error {
```
Comment (kohidave) [inline internal/pkg/aws/s3/s3.go]: Looks tricky, thanks for tackling this.

Have you looked at using the [BatchDelete](https://docs.aws.amazon.com/sdk-for-go/api/service/s3/s3manager/#BatchDelete) of the s3Manager? 

Here's a [blog post](https://aws.amazon.com/blogs/developer/aws-sdk-for-go-batch-operations-with-amazon-s3/) on how it might help simplify things.

File: internal/pkg/cli/project_delete.go [hunk 11]
```diff
@@ -182,26 +213,58 @@ func (o *deleteProjOpts) deleteEnvs() error {
...
+	proj, err := o.store.GetProject(o.ProjectName())
+	if err != nil {
+		return fmt.Errorf("get project %s: %w", o.ProjectName(), err)
+	}
+	projResources, err := o.projResourcesGetter.GetRegionalProjectResources(proj)
 	if err != nil {
+		return fmt.Errorf("get regional resources for %s: %w", proj.Name, err)
+	}
+	for _, projResource := range projResources {
+		o.spinner.Start(fmt.Sprintf("Emptying the pipeline bucket %s in %s.", color.HighlightResource(projResource.S3Bucket), projResource.Region))
```
Comment (kohidave) [inline internal/pkg/cli/project_delete.go]: I'd say move the spinner out of the loop and have it say "Cleaning up deployment resources" or something like that.

File: internal/pkg/aws/s3/s3.go (hunk 10 above)
Comment (iamhopaul123) [reply internal/pkg/aws/s3/s3.go]: Tried that method before. Ugh it is helpful when using non-versioning bucket. However, when it comes to "versioning bucket", things can be very complicated and "s3manager" they don't support versioning bucket very well, and `BatchDelete` cannot delete all the other versioning for the objects nor the "delete marker" for that.

Had a discussion with Efe yesterday on those resolved comments above on that.

Comment (kohidave) [reply internal/pkg/aws/s3/s3.go]: Ah, sorry then!

File: internal/pkg/aws/s3/s3.go [hunk 12]
```diff
@@ -52,3 +60,46 @@ func (s *Service) PutArtifact(bucket, fileName string, data io.Reader) (string,
...
+		for _, deleteMarker := range listResp.DeleteMarkers {
+			objectsToDelete = append(objectsToDelete, &s3.ObjectIdentifier{
+				Key:       deleteMarker.Key,
+				VersionId: deleteMarker.VersionId,
+			})
+		}
+		_, err = s.s3Svc.DeleteObjects(&s3.DeleteObjectsInput{
+			Bucket: aws.String(bucket),
+			Delete: &s3.Delete{
+				Objects: objectsToDelete,
```
Comment (efekarakus) [inline internal/pkg/aws/s3/s3.go]: `listResp.DeleteMarkers` + `listResp.Versions` can not be more than 1000 objects right?

File: internal/pkg/aws/s3/s3.go [hunk 13]
```diff
@@ -52,3 +60,46 @@ func (s *Service) PutArtifact(bucket, fileName string, data io.Reader) (string,
...
+			},
+		})
+		if aws.BoolValue(listResp.IsTruncated) {
+			listParams.KeyMarker = listResp.NextKeyMarker
+			listParams.VersionIdMarker = listResp.NextVersionIdMarker
+		} else {
+			return nil
+		}
```
Comment (efekarakus) [inline internal/pkg/aws/s3/s3.go]: nit: flip the if to reduce nesting
```suggestion
		if !aws.BoolValue(listResp.IsTruncated) {
			return nil
		}
		listParams.KeyMarker = listResp.NextKeyMarker
		listParams.VersionIdMarker = listResp.NextVersionIdMarker
```

File: internal/pkg/aws/s3/s3.go (hunk 10 above)
Comment (efekarakus) [reply internal/pkg/aws/s3/s3.go]: lol no problem! 

@iamhopaul123  this looks so much neater and also correct :P thanks for looking into it

File: internal/pkg/cli/interfaces.go [hunk 14]
```diff
@@ -143,3 +143,7 @@ type wsProjectManager interface {
 type artifactPutter interface {
 	PutArtifact(bucket, fileName string, data io.Reader) (string, error)
 }
+
+type bucketEmptier interface {
```
Comment (efekarakus) [inline internal/pkg/cli/interfaces.go]: 💩

File: internal/pkg/aws/s3/s3.go (hunk 12 above)
Comment (iamhopaul123) [reply internal/pkg/aws/s3/s3.go]: Yeah but `objectsToDelete` shall not exceed 1000 either, because the `list` return values limit already includes both `version` and `delete marker`

Comment (efekarakus) [reply internal/pkg/aws/s3/s3.go]: ok perfect!
