### PR TITLE
fix: delete pipeline from project

### LINKED ISSUE #735: Project delete fails in mysterious ways
```
? Are you sure you want to delete project backend? Yes
✔ Cleaning up deployment resources.
✘ Error deleting project resources.
Error: delete project resources: Waiting for stackset backend-infrastructure to be deleted: project operation 0802D5E5-E60F-4B95-AD2C-DCB4EA443D66 in stack set backend-infrastructure failed
```
This may have had something to do with the fact that the project was initiated on an older version of the cli and had traces left behind?

Checking the CFN console shows no particularly helpful information about the stackset or the stack instance.

### LINKED ISSUE #737: Deleting project should also delete the associated pipeline
When we delete a project, this should probably recommend you delete the pipeline, or even delete the pipeline on the user's behalf.

Related: https://github.com/aws/amazon-ecs-cli-v2/issues/735

### PR DESCRIPTION
**Pull request by SoManyHs**
Fixes #735
Fixes #737 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by SoManyHs** [comment]
$ archer project delete --yes
✔ Deleted app sneaky from env test.
✔ Deleted app sneaky resources from project cheeky.
✔ Deleted app sneaky from project cheeky.

? Which named profile should we use to delete test? default
✔ Deleted environment test from project cheeky.
✔ Cleaned up deployment resources.
✔ Deleted secret github-token-cheeky-aws-reinvent-2019-trivia-game.
✔ Deleted pipeline pipeline-cheeky-SoManyHs-aws-reinvent-2019-trivia-game from project cheeky.
✔ Deleted pipeline manifest from workspace.
✔ Deleted project resources.
✔ Deleted project metadata.
✔ Deleted local workspace folder.

File: internal/pkg/deploy/cloudformation/pipeline.go [hunk 1]
```diff
@@ -55,5 +55,5 @@ func (cf CloudFormation) UpdatePipeline(in *deploy.CreatePipelineInput) error {
 
 // DeletePipeline removes the CodePipeline stack.
 func (cf CloudFormation) DeletePipeline(stackName string) error {
-	return cf.cfnClient.Delete(stackName)
+	return cf.cfnClient.DeleteAndWait(stackName)
```
Comment (SoManyHs) [inline internal/pkg/deploy/cloudformation/pipeline.go:58]: Just noting for reviewers -- had to add this to ensure that the pipeline stack finished before the project stackset got deleted, since that was what was causing https://github.com/aws/amazon-ecs-cli-v2/issues/735.

File: internal/pkg/cli/project_delete.go [hunk 2]
```diff
@@ -129,6 +129,10 @@ func (o *deleteProjOpts) Execute() error {
 		return err
 	}
 
+	if err := o.deleteProjectPipeline(); err != nil {
+		return err
+	}
+
```
Comment (SoManyHs) [inline internal/pkg/cli/project_delete.go:135]: Noting for reviewers: This call must happen before `o. deleteProjectResources` and `o. deleteLocalWorkspace`, since the pipeline delete command relies on the project stackset as well as the workspace directory to still exist.

File: internal/pkg/cli/project_delete.go [hunk 3]
```diff
@@ -23,8 +23,8 @@ import (
 const (
 	defaultProfile = "default"
 
-	fmtConfirmProjectDeletePrompt = "Are you sure you want to delete project %s?"
-	confirmProjectDeleteHelp      = "Deleting a project will remove all associated resources. (apps, envs, etc.)"
+	fmtConfirmProjectDeletePrompt = "Are you sure you want to delete project %s? This will delete your project as well as any apps, environments, and pipelines."
```
Comment (efekarakus) [inline internal/pkg/cli/project_delete.go:26]: How does it look if you move the second sentence to a new line in the CLI, is it more readable? so that the line stays <80 chars
```suggestion
	fmtConfirmProjectDeletePrompt = `Are you sure you want to delete project %s? 
This will delete your project as well as any apps, environments, and pipelines.`
```

File: internal/pkg/cli/project_delete.go [hunk 4]
```diff
@@ -23,8 +23,8 @@ import (
...
+	confirmProjectDeleteHelp      = "Deleting a project will remove all associated resources. (apps, envs, pipelines, etc.)"
```
Comment (efekarakus) [inline internal/pkg/cli/project_delete.go:27]: Should we ditch this help message now that the main question is more illuminating?

File: internal/pkg/cli/project_delete.go (hunk 2 above)
Comment (efekarakus) [reply internal/pkg/cli/project_delete.go:135]: :+1: can you move this feedback to a comment in the code so that a future dev knows not to mess with the order?
Another cool move would be to have a test to ensure this property is maintained but I see that our `project_delete_tests` don't really exist 😭

File: internal/pkg/cli/project_delete.go [hunk 5]
```diff
@@ -229,7 +233,7 @@ func (o *deleteProjOpts) emptyS3Bucket() error {
 			return fmt.Errorf("empty bucket %s: %w", projResource.S3Bucket, err)
 		}
 	}
-	o.spinner.Stop(log.Ssuccess("Cleaning up deployment resources."))
+	o.spinner.Stop(log.Ssuccess("Cleaned up deployment resources."))
```
Comment (efekarakus) [inline internal/pkg/cli/project_delete.go:236]: 👏

File: internal/pkg/cli/project_delete.go [hunk 6]
```diff
@@ -268,6 +272,21 @@ func (o *deleteProjOpts) deleteLocalWorkspace() error {
...
+		SkipConfirmation: true,
+		DeleteSecret:     true,
+	}
+
+	deletePipelineOpts, err := newDeletePipelineOpts(vars)
+	if err != nil {
+		return err
+	}
+
+	return deletePipelineOpts.Run()
```
Comment (efekarakus) [inline internal/pkg/cli/project_delete.go:287]: since we construct the `vars` ourselves we prob don't need the `Run()` method and call `Execute()` directly

Comment (SoManyHs) [reply internal/pkg/cli/project_delete.go:287]: True, but it makes the error handling a little less verbose, plus it still does the validation that helps with debugging. The "Ask" is still in there but it'll get skipped since we'll always skipConfirmation.

File: internal/pkg/cli/project_delete.go (hunk 4 above)
Comment (SoManyHs) [reply internal/pkg/cli/project_delete.go:27]: Hmmm, maybe? I don't see the harm in keeping it in there for consistency tho
