### PR TITLE
Display progress texts while deploying an environment

### LINKED ISSUE #264: Display progress of environment during creation
## Story
As a user that ran `env init`,  
I want to see _indicators_ that the environment is getting created,  
So that I know what's created, or if my request is stuck.  

#### Happy scenario
```
$ archer env init test
🔄 Creating the infrastructure for the "test" environment
- Virtual private cloud on 2 availability zones to hold your services      [created]
  - Internet gateway to connect the network to the internet                [created]
  - Routing tables for services to talk with each other                    [creating]
  - Public subnets for internet facing services                            [created]
  - NAT gateway for private services to send requests to the internet      [created]
  - Private subnets for services that can't be reached from the internet   [created]
- ECS Cluster to hold your services                                        [created]
- Application load balancer to distribute traffic                          [creating]
```
after 20 mins 😴
```
$ archer env init test
✅ Created the infrastructure for the "test" environment
- Virtual private cloud on 2 availability zones to hold your services      [created]
  - Internet gateway to connect the network to the internet                [created]
  - Routing tables for services to talk with each other                    [created]
  - Public subnets for internet facing services                            [created]
  - NAT gateway for private services to send requests to the internet      [created]
  - Private subnets for services that can't be reached from the internet   [created]
- ECS Cluster to hold your services                                        [created]
- Application load balancer to distribute traffic                          [created]
```
#### Bad scenario
```
$ archer env init test
❌ Failed to create the infrastructure for the "test" environment
- Virtual private cloud on 2 availability zones to hold your services      [created]
   - Internet gateway to connect the network to the internet                [failed]
   {AWS ERROR MESSAGE}
```

### PR DESCRIPTION
**Pull request by efekarakus**
Resolves #264

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: internal/pkg/cli/progress.go [hunk 1]
```diff
@@ -12,3 +20,107 @@ type progress interface {
 	// Events writes additional information in between the start and stop stages.
 	Events([]string)
 }
+
```
Comment (efekarakus) [inline internal/pkg/cli/progress.go]: I'd like to get feedback on whether y'all think there is a more appropriate package to put these types and functions?

I thought maybe the `term/spinner` pkg since it's about transforming `[]deploy.ResourceEvent` to a `[]string` that the `term/spinner` pkg understands.

File: internal/pkg/term/color/color.go [hunk 2]
```diff
@@ -13,16 +13,25 @@ import (
...
 )
 
-const colorEnvVar = "COLOR"
-
-var lookupEnv = os.LookupEnv
+// String markers to denote the status of an operation.
+var (
+	SuccessMarker = color.HiGreenString("✔")
+	ErrorMarker   = color.HiRedString("✘")
+)
```
Comment (efekarakus) [inline internal/pkg/term/color/color.go]: self note: I need to move these to a separate file so that they're rendered for windows

File: internal/pkg/cli/env.go [hunk 3]
```diff
@@ -16,7 +15,7 @@ import (
 // environmentDeployer can deploy an environment.
 type environmentDeployer interface {
 	DeployEnvironment(env *deploy.CreateEnvironmentInput) error
-	WaitForEnvironmentCreation(env *deploy.CreateEnvironmentInput) (*archer.Environment, error)
+	StreamEnvironmentCreation(env *deploy.CreateEnvironmentInput) (<-chan []deploy.ResourceEvent, <-chan deploy.CreateEnvironmentResponse)
```
Comment (SoManyHs) [inline internal/pkg/cli/env.go]: omg a go channel! in the wild! 🔭

File: internal/pkg/cli/env_init.go [hunk 4]
```diff
@@ -60,7 +63,7 @@ func (opts *InitEnvOpts) Validate() error {
 			return err
 		}
 	}
-	if viper.GetString(projectFlag) == "" {
+	if opts.projectName == "" {
 		return errors.New("no project found, run `project init` first")
```
Comment (SoManyHs) [inline internal/pkg/cli/env_init.go]: ..."plz"

File: internal/pkg/term/progress/deploy.go [hunk 5]
```diff
@@ -0,0 +1,73 @@
...
+	"strings"
+
+	"github.com/aws/amazon-ecs-cli-v2/internal/pkg/deploy"
+	"github.com/aws/amazon-ecs-cli-v2/internal/pkg/term/color"
+)
+
+// ResourceMatcher is a function that returns true if the resource event matches a criteria.
+type ResourceMatcher func(deploy.Resource) bool
+
+// HumanizeResourceEvents groups raw deploy events under human-friendly progress texts that can be passed into the Events() method.
```
Comment (SoManyHs) [inline internal/pkg/term/progress/deploy.go]: Nit: Can we wrap this at a narrow tab width?

File: internal/pkg/term/progress/progress.go [hunk 6]
```diff
@@ -0,0 +1,19 @@
+// Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
+// SPDX-License-Identifier: Apache-2.0
+
+// Package progress provides data and functionality to display updates to the terminal.
+package progress
+
+// Text is a description of the progress update.
+type Text string
+
+// Status is the condition of the progress update.
```
Comment (SoManyHs) [inline internal/pkg/term/progress/progress.go]: Is it redundant to specify that these are defined by CFN?

File: internal/pkg/cli/env_init.go [hunk 7]
```diff
@@ -69,53 +72,100 @@ func (opts *InitEnvOpts) Validate() error {
...
+		return fmt.Errorf("store environment: %w", err)
 	}
-	opts.prog.Stop("Done!")
 	log.Successf("Created environment %s in region %s under project %s.\n",
-		color.HighlightUserInput(env.Name), color.HighlightResource(env.Region), color.HighlightResource(env.Project))
+		color.HighlightUserInput(resp.Env.Name), color.HighlightResource(resp.Env.Region), color.HighlightResource(resp.Env.Project))
 	return nil
 }
 
+func (opts *InitEnvOpts) humanizeEnvironmentEvents(resourceEvents []deploy.ResourceEvent) []termprogress.TabRow {
```
Comment (kohidave) [inline internal/pkg/cli/env_init.go]: I feel like this should live closer to the deploy package.

File: internal/pkg/term/progress/deploy.go [hunk 8]
```diff
@@ -0,0 +1,81 @@
+// Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
```
Comment (kohidave) [inline internal/pkg/term/progress/deploy.go]: Just a thought experiment - is this implementation specific to CloudFormation? If so, should we call this file CloudFormation?

File: internal/pkg/cli/env_init.go (hunk 4 above)
Comment (efekarakus) [reply internal/pkg/cli/env_init.go]: Done

File: internal/pkg/cli/env_init.go (hunk 7 above)
Comment (efekarakus) [reply internal/pkg/cli/env_init.go]: The struggle is that the `textVPC`, ... constants I think should be in the `cli` package or some sort of view package.

I'll keep them here for now, let me know if you can think of a better place

File: internal/pkg/term/progress/deploy.go (hunk 8 above)
Comment (efekarakus) [reply internal/pkg/term/progress/deploy.go]: The idea for the `deploy` package was for it to be be agnostic of the underlying tool used to do the deployment (cfn vs. something else)

That's why I named this file `deploy.go`.  I agree that the `deploy.Resource` struct is a bit too CFN specific with `LogicalName` and `Type` as fields :| 
I thought that a resource name and  type would be there no matter what type of deployment

File: internal/pkg/term/progress/deploy.go (hunk 5 above)
Comment (efekarakus) [reply internal/pkg/term/progress/deploy.go]: Done!

File: internal/pkg/term/progress/progress.go (hunk 6 above)
Comment (efekarakus) [reply internal/pkg/term/progress/progress.go]: I was trying to go for Statuses that are agnostic of the type of deployment (cfn vs manual for example). Tbh though, right now they only work for CFN statuses :P

I think `HumanizeResourceEvents` needs a nicer interface that can take any piece of string (like a cfn status) and transform it to a type `progress.Status`.

Soon™️
