### PR TITLE
fix: change app show output and refactor validate and ask

### LINKED ISSUE #577: fix `app show` human output format
### The interactive experience
```
$ ecs-preview app show
? Which application would you like to show?
> my-app

General

    AppName   "my-app"
    Type      "lb-application"
    Project   "my-project"

Deploys

    EnvName     "test"
    AccountID   "123456789"
    Region      "us-west-2"
    Prod        false
    Port        "8080"
    Tasks       3
    CPU         "256"
    Memory      "512"
    Path        "*"
    URL         "flask-Ec2Se-KCH5OLWN57WM-992971783.us-west-2.elb.amazonaws.com"
```

We can always add more colors to make it fancier.

### PR DESCRIPTION
**Pull request by iamhopaul123**
Fix #577.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by iamhopaul123** [comment]
##Manual Test

```$ archer app show -a my-app --json | jq .```
```
{
  "appName": "my-app",
  "type": "Load Balanced Web App",
  "project": "my-project",
  "deployConfig": [
    {
      "environment": "test",
      "port": "5000",
      "tasks": "1",
      "cpu": "256",
      "memory": "512",
      "url": "my-pr-Publi-UX7AU6UI412C-1003834689.us-west-2.elb.amazonaws.com",
      "path": "*"
    }
  ]
}
```

```$ archer app show -a my-app```
```
About

  Project           my-project
  Name              my-app
  Type              Load Balanced Web App

Configurations

  Environment       CPU (vCPU)          Memory (MiB)        Port                Tasks
  test              0.25                512                 5000                1

Routes

  Environment       URL                                                              Path
  test              my-pr-Publi-UX7AU6UI412C-1003834689.us-west-2.elb.amazonaws.com  *
```

File: internal/pkg/cli/app_show.go [hunk 1]
```diff
@@ -30,36 +28,28 @@ const (
...
-	AppName      string                    `json:"appName"`
-	Type         string                    `json:"type"`
-	Project      string                    `json:"project"`
-	Account      string                    `json:"account"`
-	Environments []serializedWebAppEnv     `json:"environments"`
-	Services     []serializedWebAppService `json:"services"`
+	AppName       string                   `json:"appName"`
+	Type          string                   `json:"type"`
+	Project       string                   `json:"project"`
+	DeployConfigs []serializedWebAppConfig `json:"deployConfig"`
```
Comment (sonofachamp) [inline internal/pkg/cli/app_show.go]: `"deployConfig"` -> `"deployConfigs"`

File: internal/pkg/cli/app_show.go [hunk 2]
```diff
@@ -72,109 +62,100 @@ type ShowAppOpts struct {
...
+func (o *ShowAppOpts) Validate() error {
+	if o.ProjectName() != "" {
+		names, err := o.retrieveProjects()
 		if err != nil {
 			return err
 		}
-		opts.projectName = projectName
+		if !contains(o.ProjectName(), names) {
+			return fmt.Errorf("project '%s' does not exist in the workspace", o.ProjectName())
+		}
```
Comment (sonofachamp) [inline internal/pkg/cli/app_show.go]: Are we prompting for a project name and then returning an error if the selected project name isn't part of the local workspace? Should we instead simply error out if a local workspace isn't detected?

File: internal/pkg/cli/app_show.go [hunk 3]
```diff
@@ -72,109 +62,100 @@ type ShowAppOpts struct {
...
+	if err := o.askProject(); err != nil {
+		return err
+	}
+	return o.askAppName()
+}
+
+// Validate returns an error if the values provided by the user are invalid.
+func (o *ShowAppOpts) Validate() error {
+	if o.ProjectName() != "" {
+		names, err := o.retrieveProjects()
```
Comment (sonofachamp) [inline internal/pkg/cli/app_show.go]: We already called `o.retrieveProjects` in the `askProject` method. Can we stash the result from the first call instead of making another network call?

File: internal/pkg/cli/app_show.go [hunk 4]
```diff
@@ -72,109 +62,100 @@ type ShowAppOpts struct {
...
 
 	return nil
 }
 
 // Execute shows the applications through the prompt.
-func (opts *ShowAppOpts) Execute() error {
-	if opts.appName != "" {
-		if err := opts.retrieveData(); err != nil {
+func (o *ShowAppOpts) Execute() error {
+	if o.appName != "" {
```
Comment (sonofachamp) [inline internal/pkg/cli/app_show.go]: Is it possible to get to this point with an empty `appName`?

File: internal/pkg/cli/app_show.go (hunk 2 above)
Comment (kohidave) [reply internal/pkg/cli/app_show.go]: I think this is if someone passes in a project flag.

File: internal/pkg/cli/app_show.go (hunk 4 above)
Comment (iamhopaul123) [reply internal/pkg/cli/app_show.go]: Yes, if there is no application in the project. Since we don't want to error out, instead we want to show no applications. If there's no application to list, we don't need users to select and the `appName` will be set to an empty string.

File: internal/pkg/cli/app_show.go (hunk 2 above)
Comment (iamhopaul123) [reply internal/pkg/cli/app_show.go]: So I had the same question and had an offline discussion with Efe. We think for `show` it might not be necessary for users to stay in a local workspace. If they are not in a local ws then we can prompt them to select the project. What do you think?

File: internal/pkg/cli/app_show.go (hunk 4 above)
Comment (sonofachamp) [reply internal/pkg/cli/app_show.go]: So should we simply print a message indicating "no apps found" and return nil, or maybe add a comment indicating that scenario?

File: internal/pkg/cli/app_show.go (hunk 2 above)
Comment (sonofachamp) [reply internal/pkg/cli/app_show.go]: But this is forcing you to be in a workspace, right? `o.ProjectName()` is populated by being in a local workspace?

File: internal/pkg/cli/app_show.go (hunk 4 above)
Comment (iamhopaul123) [reply internal/pkg/cli/app_show.go]: Yeah I'll print a log message saying "no applications found in project %s".

File: internal/pkg/cli/app_show.go (hunk 2 above)
Comment (iamhopaul123) [reply internal/pkg/cli/app_show.go]: Not necessary I think, if you are not in a workspace it will prompt you to choose a project.

File: internal/pkg/cli/app_show.go [hunk 5]
```diff
@@ -30,36 +29,42 @@ const (
...
 
 // ShowAppOpts contains the fields to collect for showing an application.
 type ShowAppOpts struct {
-	ShouldOutputJSON bool
+	shouldOutputJSON  bool
+	shouldOutputInfra bool
 
-	proj *archer.Project
-	app  serializedWebApp
+	app serializedWebApp
```
Comment (efekarakus) [inline internal/pkg/cli/app_show.go]: nit: is there a benefit of storing this in the state? instead of returning it in `retrieveData`?

File: internal/pkg/cli/app_show.go [hunk 6]
```diff
@@ -72,109 +77,121 @@ type ShowAppOpts struct {
...
 			return fmt.Errorf("retrieving application URI: %w", err)
 		}
 	}
-	opts.app.Environments = serializedEnvs
-	opts.app.Services = serializedServices
+	o.app.Configurations = serializedDeployConfigs
+	o.app.Routes = serializedWebAppRoutes
+
+	if o.shouldOutputInfra {
+		var serializedWebAppInfras []serializedWebAppInfra
```
Comment (efekarakus) [inline internal/pkg/cli/app_show.go]: nit: s/serializedWebAppInfras/resources

File: internal/pkg/cli/app_show.go [hunk 7]
```diff
@@ -72,109 +77,121 @@ type ShowAppOpts struct {
...
+				continue
+			}
+			if !applicationNotDeployed(err) {
+				return fmt.Errorf("retrieving application infrastructures: %w", err)
+			}
+		}
+		o.app.Infrastructures = serializedWebAppInfras
+	}
 
 	return nil
```
Comment (efekarakus) [inline internal/pkg/cli/app_show.go]: nit: style, I prefer to return the struct at the end instead of initializing fields in multiple locations
```go
return &serializedWebApp{
	AppName: app.Name,
	...
	Resources: resources,
}, nil
```

File: internal/pkg/cli/app_show.go [hunk 8]
```diff
@@ -198,82 +215,126 @@ func applicationNotDeployed(err error) bool {
...
+func (o *ShowAppOpts) humanOutput() {
+	writer := tabwriter.NewWriter(o.w, minCellWidth, tabWidth, cellPaddingWidth, paddingChar, noAdditionalFormatting)
+	fmt.Fprintf(writer, color.Bold.Sprint("About\n\n"))
+	writer.Flush()
+	fmt.Fprintf(writer, "  %s\t%s\n", "Project", o.app.Project)
+	fmt.Fprintf(writer, "  %s\t%s\n", "Name", o.app.AppName)
+	fmt.Fprintf(writer, "  %s\t%s\n", "Type", o.app.Type)
+	fmt.Fprintf(writer, color.Bold.Sprint("\nConfigurations\n\n"))
+	writer.Flush()
+	fmt.Fprintf(writer, "  %s\t%s\t%s\t%s\t%s\n", "Environment", "CPU (vCPU)", "Memory (MiB)", "Port", "Tasks")
```
Comment (efekarakus) [inline internal/pkg/cli/app_show.go]: nit: can we move `Tasks` right after `Environment` instead of at the end?

File: internal/pkg/cli/app_show.go [hunk 9]
```diff
@@ -198,82 +215,126 @@ func applicationNotDeployed(err error) bool {
...
+			parsedInfra := parseResourcesArn(infra)
+			fmt.Fprintf(writer, "  %s\t%s\t%s\t%s\n", parsedInfra.Environment, parsedInfra.ServiceID, parsedInfra.TaskDefinitionID, parsedInfra.TargetGroupID)
+		}
 	}
 	writer.Flush()
 }
 
-func (opts *ShowAppOpts) jsonOutput() (string, error) {
-	b, err := json.Marshal(opts.app)
+func parseResourcesArn(infra serializedWebAppInfra) *serializedWebAppInfra {
```
Comment (efekarakus) [inline internal/pkg/cli/app_show.go]: I'm not commenting on these since it's going to change :)

File: internal/pkg/cli/app_show.go [hunk 10]
```diff
@@ -198,82 +215,126 @@ func applicationNotDeployed(err error) bool {
...
+	} else {
+		res.TargetGroupID = targetGroup[1]
+	}
+	return res
+}
+
+func cpuToString(s string) string {
+	cpuInt, _ := strconv.Atoi(s)
+	cpuFloat := float64(cpuInt) / 1024
+	return fmt.Sprintf("%g", cpuFloat)
```
Comment (efekarakus) [inline internal/pkg/cli/app_show.go]: nice magic

File: internal/pkg/describe/webapp.go [hunk 11]
```diff
@@ -16,12 +16,25 @@ import (
...
 	DNSName string // The environment's subdomain if the application is served on HTTPS. Otherwise, the public load balancer's DNS.
 	Path    string // Empty if the application is served on HTTPS. Otherwise, the pattern used to match the application.
 }
 
+// WebAppResources contains application resources created by cloudformation.
+type WebAppResources struct {
+	Service        string
+	TargetGroup    string
+	TaskDefinition string
+}
```
Comment (efekarakus) [inline internal/pkg/describe/webapp.go]: Based on our discussion, maybe we can change this to be a generic struct for CFN resources
```go
type CfnResource struct {
    PhysicalID
    Type
}
```

File: internal/pkg/describe/webapp.go [hunk 12]
```diff
@@ -102,6 +116,25 @@ func (d *WebAppDescriber) ECSParams(envName string) (*WebAppECSParams, error) {
 	}, nil
 }
 
+// StackResources returns the physical ID of stack resources created by cloudformation.
+func (d *WebAppDescriber) StackResources(envName string) (*WebAppResources, error) {
```
Comment (efekarakus) [inline internal/pkg/describe/webapp.go]:
```suggestion
func (d *WebAppDescriber) StackResources(envName string) ([]*CfnResource, error) {
```

File: internal/pkg/cli/app_show.go (hunk 2 above)
Comment (sonofachamp) [reply internal/pkg/cli/app_show.go]: Oh yeah I think you're right. I keep thinking `Validate` happens after `Ask`, but it's the other way around.

File: internal/pkg/describe/webapp.go [hunk 13]
```diff
@@ -156,6 +189,32 @@ func (d *WebAppDescriber) appParams(env *archer.Environment) (map[string]string,
...
+		return nil, err
+	}
+	resources := make(map[string]string)
+	for _, appResource := range appResource {
+		resources[*appResource.LogicalResourceId] = *appResource.PhysicalResourceId
+	}
+	return resources, nil
+}
+
+func (d *WebAppDescriber) resource(roleARN, region, stackName string) ([]*cloudformation.StackResource, error) {
```
Comment (efekarakus) [inline internal/pkg/describe/webapp.go]: nit: 
```suggestion
func (d *WebAppDescriber) describeStackResources(roleARN, region, stackName string) ([]*cloudformation.StackResource, error) {
```

File: internal/pkg/term/color/color.go [hunk 14]
```diff
@@ -20,6 +20,7 @@ var (
 	Red        = color.New(color.FgHiRed)
 	Cyan       = color.New(color.FgCyan)
 	HiCyan     = color.New(color.FgHiCyan)
+	Bold       = color.New(color.Bold)
 	BoldItalic = color.New(color.Bold).Add(color.Italic)
```
Comment (efekarakus) [inline internal/pkg/term/color/color.go]: BoldItalic = Bold.Add(color.Italic)

File: internal/pkg/cli/app_show.go [hunk 15]
```diff
@@ -72,109 +77,125 @@ type ShowAppOpts struct {
...
+// Validate returns an error if the values provided by the user are invalid.
+func (o *ShowAppOpts) Validate() error {
+	if o.ProjectName() != "" {
+		names, err := o.retrieveProjects()
 		if err != nil {
 			return err
 		}
-		opts.projectName = projectName
+		if !contains(o.ProjectName(), names) {
+			return fmt.Errorf("project '%s' does not exist in the workspace", o.ProjectName())
```
[the remark this answers is not in the document]
Comment (iamhopaul123) [reply internal/pkg/cli/app_show.go]: I borrowed this from app_package. Yeah I guess we can use GetProject and GetApplication

File: internal/pkg/term/color/color.go (hunk 14 above)
Comment (iamhopaul123) [reply internal/pkg/term/color/color.go]: Probably no. This `Add()` has side effect which can add "Italic" to `Bold` if we do that.

File: internal/pkg/cli/app_show.go (hunk 15 above)
[the remark this answers is not in the document]
Comment (efekarakus) [reply internal/pkg/cli/app_show.go]: blame my own crappy code, i see how it is

File: internal/pkg/describe/webapp.go [hunk 16]
```diff
@@ -34,8 +40,35 @@ type TaskSize struct {
...
+
+// SerializedWebApp contains serialized parameters for a web application.
+type SerializedWebApp struct {
+	AppName        string                    `json:"appName"`
+	Type           string                    `json:"type"`
+	Project        string                    `json:"project"`
+	Configurations []SerializedWebAppConfig  `json:"configurations"`
+	Routes         []SerializedWebAppRoute   `json:"routes"`
+	Resources      map[string][]*CfnResource `json:"resources,omitempty"`
+}
```
Comment (sonofachamp) [inline internal/pkg/describe/webapp.go]: Should we remove the word `Serialized` from these constructs?

Comment (iamhopaul123) [reply internal/pkg/describe/webapp.go]: I personally prefer to keep `Serialized` because as you might notice that we have `WebAppECSParams` struct with very similar member variable set as `SerializedWebAppConfig`. The former struct is when we fetch those parameters while the latter is used for output, and `Serialized` identifier makes the usage for those structs stand out.

Comment (sonofachamp) [reply internal/pkg/describe/webapp.go]: I disagree because serialization is a form the data might take from the structure, so I find including it in the name confusing, but it's not a big deal.

Comment (iamhopaul123) [reply internal/pkg/describe/webapp.go]: Oh I get your point :+1: `Serialized` is not a good one.

File: internal/pkg/cli/app_show.go [hunk 17]
```diff
@@ -71,112 +43,120 @@ type ShowAppOpts struct {
...
-		opts.humanOutput()
+		o.humanOutput(app)
 	}
 
 	return nil
 }
 
-func (opts *ShowAppOpts) retrieveData() error {
-	app, err := opts.storeSvc.GetApplication(opts.ProjectName(), opts.appName)
+func (o *ShowAppOpts) retrieveData() (*describe.WebApp, error) {
```
Comment (efekarakus) [inline internal/pkg/cli/app_show.go]: I wonder if this method should belong to the `describer` instead since it returns a struct from the same package `describe.WebApp`? Same for `humanOutput` and `jsonOutput`

Here is what I'm thinking:
```go
webApp := o.describer.Describe()

s, err := webApp.HumanString() // returns the string from `func (o *ShowAppOpts) humanOutput(app *describe.WebApp)`
s, err := webApp.JSONString() // returns the string from `func (o *ShowAppOpts) jsonOutput(app *describe.WebApp) (string, error)`
```

The main benefit of this approach is that we can take dependencies on `HumanStringer` and `JSONStringer` interfaces in the future to describe different type of applications without changing the `app show` command significantly.

**Comment by kohidave** [comment]
It's so pretty. THANK YOU!
