### PR TITLE
chore(cli): refactoring to project init and bug fix

### LINKED ISSUE #765: Alert users when trying to create an existing project
As discussed [here](https://github.com/aws/amazon-ecs-cli-v2/pull/763#discussion_r395862302), since we make this `project init` subcommand idempotent, which means users might accidentally overwrite sth because for project we pass in config via flags. We should double check with users when they are about to create a project that already exists in SSM.

### LINKED ISSUE #766: project name argument for project init gets ignored by local project name
Currently if there's already a local project named "bot-project", and users run `project init my-project` again, it will not throw any error even if there appears to be an obvious conflict. Instead, the argument for project name (which is "my-project") just gets ignored.

Example:

```
$ ecs-preview project init bot-project
Looks like you are using a workspace that's registered to project my-project.
We'll use that as your project instead of bot-project.
✔ Created the infrastructure to manage container repositories under project my-project.
✔ The directory ecs-project will hold application manifests for project my-project.

Recommended follow-up actions:
- Run `ecs-preview init` to add a new application to your project.
```

### PR DESCRIPTION
**Pull request by iamhopaul123**
Fix #766, fix #765.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by iamhopaul123** [comment]
## Manual Test

1. Already have "my-project" locally, and want to init a project with name "bot-project"
```
$ ecs-preview project init bot-project
Error: project init cancelled - name conflict between bot-project and local project name my-project
```

2. Already have "my-project" locally, and want to init "my-project" again by using flag.
```
$ ecs-preview project init my-project

? Project my-project already exists, would you like to use it? Yes
✔ Created the infrastructure to manage container repositories under project my-project.
✔ The directory ecs-project will hold application manifests for project my-project.

Recommended follow-up actions:
- Run `ecs-preview init` to add a new application to your project.
```

3. Already have "my-project" locally, and want to init "my-project" again.
```
$ ecs-preview project init
Looks like you are using a workspace that's registered to project my-project.
We'll use that as your project.
✔ Created the infrastructure to manage container repositories under project my-project.
✔ The directory ecs-project will hold application manifests for project my-project.

Recommended follow-up actions:
- Run `ecs-preview init` to add a new application to your project.
```

4. Do not have any project and want to init "my-project"
```
$ ecs-preview project init
Looks like you have some projects already.

? Would you like to use one of your existing projects? No
Ok, let's create a new project then.

? What would you like to name your project? my-project
✔ Created the infrastructure to manage container repositories under project my-project.
✔ The directory ecs-project will hold application manifests for project my-project.

Recommended follow-up actions:
- Run `ecs-preview init` to add a new application to your project.
```

File: internal/pkg/cli/project_init.go [hunk 1]
```diff
@@ -79,25 +93,24 @@ func (o *initProjectOpts) Validate() error {
...
+		if o.ProjectName == "" {
+			log.Infoln(fmt.Sprintf(
+				"Looks like you are using a workspace that's registered to project %s.\nWe'll use that as your project.",
+				color.HighlightResource(summary.ProjectName)))
+			o.ProjectName = summary.ProjectName
+			return nil
+		}
+		if o.ProjectName != summary.ProjectName {
+			// Error out if project name specified by flag is different from the one in workspace.
+			return fmt.Errorf("project init cancelled - name conflict between %s and local project name %s", o.ProjectName, summary.ProjectName)
```
Comment (efekarakus) [inline internal/pkg/cli/project_init.go]: maybe: 
```go
log.Errorf(`Workspace is already registered with project %s instead of %s.
  If you'd like to delete the project locally, you can remove the %s directory.
  If you'd like to delete project %s and all of its resources, run %s.`,
  summary.ProjectName,
  o.ProjectName,
  workspace.ProjectDirectoryName,
  color.HighlightCode("ecs-preview project delete"))
return fmt.Errorf("workspace already registered with %s", summary.ProjectName)
```

File: internal/pkg/cli/project_init.go [hunk 2]
```diff
@@ -151,6 +156,62 @@ func (o *initProjectOpts) Execute() error {
...
+		}
+		return err
+	}
+	confirm, err := o.prompt.Confirm(fmt.Sprintf("Project %s already exists, would you like to use it?", projectName), "", prompt.WithTrueDefault())
+	if err != nil {
+		return fmt.Errorf("prompt to confirm using existing project: %w", err)
+	}
+	if !confirm {
+		return fmt.Errorf("project init cancelled - no changes made")
+	}
```
Comment (efekarakus) [inline internal/pkg/cli/project_init.go]: Is this needed? If I understand correctly, the user explicitly told us that they want to use this `projectName` we can probably skip this prompt.

File: internal/pkg/cli/project_init.go [hunk 3]
```diff
@@ -151,6 +156,62 @@ func (o *initProjectOpts) Execute() error {
...
+
+	return nil
+}
+
+func (o *initProjectOpts) validateDomain(domainName string) error {
+	domainExist := false
```
Comment (efekarakus) [inline internal/pkg/cli/project_init.go]: What do you think of putting this functionality in the `route53` package instead?

Comment (iamhopaul123) [reply internal/pkg/cli/project_init.go]: :+1: good idea

File: internal/pkg/cli/project_init.go (hunk 2 above)
Comment (iamhopaul123) [reply internal/pkg/cli/project_init.go]: Yeah so this is to help users avoid accidentally overwriting some config for their existing project. If the project that they specify does not exist then this confirm prompt will not show up.

File: internal/pkg/aws/route53/route53.go [hunk 4]
```diff
@@ -1,16 +1,38 @@
...
+	return &Route53{
+		// See https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DNSLimitations.html#limits-service-quotas
+		// > To view limits and request higher limits for Route 53, you must change the Region to US East (N. Virginia).
+		// So we have to set the region to us-east-1 to be able to find out if a domain name exists in the account.
+		client: route53.New(s, aws.NewConfig().WithRegion("us-east-1")),
+	}
+}
+
+// hostedZoneExists checks if certain domain exists in any of the hosted zones.
+func (r *Route53) hostedZoneExists(hostedZones []*route53.HostedZone, domain string) bool {
```
Comment (efekarakus) [inline internal/pkg/aws/route53/route53.go]: This can remain as a function since it doesn't use the client.

Comment (efekarakus) [reply internal/pkg/aws/route53/route53.go]: Also nice we even got to make this private :D

File: internal/pkg/cli/project_init.go (hunk 2 above)
Comment (efekarakus) [reply internal/pkg/cli/project_init.go]: how can users bypass this prompt? normally each prompt should have a corresponding flag.
As far as I can tell, if the `projectName` already exists and the workspace is registered with a different name we will error out so we shouldn't be able to overwrite a file?

I might be missing something though

Comment (iamhopaul123) [reply internal/pkg/cli/project_init.go]: If they created "my-project" then they do "project init my-project --domain example.com" again, without this confirmation then its domain name can be overwritten.

File: internal/pkg/aws/route53/route53.go [hunk 5]
```diff
@@ -1,16 +1,60 @@
...
+type route53Client interface {
+	ListHostedZonesByName(in *route53.ListHostedZonesByNameInput) (*route53.ListHostedZonesByNameOutput, error)
+}
+
+// Route53 wraps an Route53 client.
+type Route53 struct {
+	client route53Client
+}
+
+// New returns a Route53 strict configured against the input session.
```
Comment (bvtujo) [inline internal/pkg/aws/route53/route53.go]: typo: struct 😇

File: internal/pkg/cli/project_init.go (hunk 2 above)
Comment (efekarakus) [reply internal/pkg/cli/project_init.go]: ah I see! mmm this is very tricky. If suddenly they provide a domain while one doesn't exist, then they'd also need to update their environments and application I think 🤔 .

I wonder if the right thing to do is throwing an error saying that a `project named "%s" already exists with a different configuration %s`

File: internal/pkg/aws/route53/route53.go [hunk 6]
```diff
@@ -1,16 +1,60 @@
...
+			return true, nil
+		}
+		if !aws.BoolValue(resp.IsTruncated) {
+			return false, nil
+		}
+		in = &route53.ListHostedZonesByNameInput{DNSName: resp.NextDNSName, HostedZoneId: resp.NextHostedZoneId}
+		resp, err = r.client.ListHostedZonesByName(in)
+		if err != nil {
+			return false, fmt.Errorf("list hosted zone for %s: %w", domainName, err)
+		}
```
[the remark this answers is not in the document]
Comment (SoManyHs) [reply internal/pkg/aws/route53/route53.go]: (I see now that it was moved from elsewhere, so not a big deal -- feel free to ignore)

File: internal/pkg/cli/project_init.go [hunk 7]
```diff
@@ -151,6 +161,42 @@ func (o *initProjectOpts) Execute() error {
...
+	}
+	proj, err := o.projectStore.GetProject(projectName)
+	if err != nil {
+		var noSuchProjectErr *store.ErrNoSuchProject
+		if errors.As(err, &noSuchProjectErr) {
+			return nil
+		}
+		return fmt.Errorf("get project %s: %w", projectName, err)
+	}
+	if proj.Domain != o.DomainName {
```
Comment (efekarakus) [inline internal/pkg/cli/project_init.go]: I wonder if we can use https://golang.org/pkg/reflect/#DeepEqual to check if the two objects differ

Comment (iamhopaul123) [reply internal/pkg/cli/project_init.go]: I think we should be good. `Project` has projectName (must be the same), accountID (must be the same as well otherwise `GetProject` won't get this project). Not sure if I missed anything?

Comment (efekarakus) [reply internal/pkg/cli/project_init.go]: hehe that's because I'm adding `Tags` now as a field to a project :P https://github.com/aws/amazon-ecs-cli-v2/pull/779/files so i wanted that to error out too if it's different. But I can do that change in my PR :)
