### PR TITLE
fix: move json and human output tests from cli to describe test file

### LINKED ISSUE #913: (fix): move env show unit tests
The unit tests for JSON and Human outputs are currently in the Execute section of cli/env_show_test.go, but belong in describe/env_test.go, as the JSONString and HumanString methods are in describe/env.go.

### PR DESCRIPTION
**Pull request by huanjani**
Fixes #913 

Moved JSONString and HumanString unit tests from cli/env_show_test.go to describe/env_test.go and changed test data to be consistent with the rest of the test file. Added a failure test case to TestEnvShow_Execute.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: internal/pkg/describe/env_test.go [hunk 1]
```diff
@@ -152,3 +152,155 @@ func TestEnvDescriber_Describe(t *testing.T) {
 		})
 	}
 }
+
+func TestEnvDescriber_JSONString(t *testing.T) {
```
Comment (efekarakus) [inline internal/pkg/describe/env_test.go:156]: should this be: `TestEnvDescription_JSONString`?

File: internal/pkg/describe/env_test.go [hunk 2]
```diff
@@ -152,3 +152,155 @@ func TestEnvDescriber_Describe(t *testing.T) {
...
+		Project: "testProject",
+		Name:    "testApp3",
+		Type:    "load-balanced",
+	}
+	allApps := []*archer.Application{testApp1, testApp2, testApp3}
+	testCases := map[string]struct {
+		setupMocks func(mocks envDescriberMocks)
+
+		shouldOutputJSON bool
+		wantedError      error
```
Comment (efekarakus) [inline internal/pkg/describe/env_test.go:191]: are these used?

File: internal/pkg/describe/env.go [hunk 3]
```diff
@@ -1,6 +1,3 @@
-// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
```
Comment (efekarakus) [inline internal/pkg/describe/env.go:1]: We should probably keep this :P

File: internal/pkg/describe/env_test.go [hunk 4]
```diff
@@ -152,3 +152,155 @@ func TestEnvDescriber_Describe(t *testing.T) {
...
+		wantedContent    string
+	}{
+		"correctly shows json output": {
+			shouldOutputJSON: true,
+			wantedContent:    "{\"environment\":{\"project\":\"testProject\",\"name\":\"testEnv\",\"region\":\"us-west-2\",\"accountID\":\"123456789012\",\"prod\":false,\"registryURL\":\"\",\"executionRoleARN\":\"\",\"managerRoleARN\":\"\"},\"applications\":[{\"project\":\"testProject\",\"name\":\"testApp1\",\"type\":\"load-balanced\"},{\"project\":\"testProject\",\"name\":\"testApp2\",\"type\":\"load-balanced\"},{\"project\":\"testProject\",\"name\":\"testApp3\",\"type\":\"load-balanced\"}],\"tags\":{\"key1\":\"value1\",\"key2\":\"value2\"}}\n",
+		},
+	}
+
+	for name, tc := range testCases {
+		t.Run(name, func(t *testing.T) {
```
Comment (efekarakus) [inline internal/pkg/describe/env_test.go:201]: We only have to write [table-driven tests](https://dave.cheney.net/2019/05/07/prefer-table-driven-tests) if we are testing different cases. In this situation we don't, so we can get rid of the `map` and for-loop.

File: internal/pkg/describe/env_test.go (hunk 1 above)
Comment (huanjani) [reply internal/pkg/describe/env_test.go:156]: Oh, yes! Thanks!

File: internal/pkg/describe/env.go (hunk 3 above)
Comment (huanjani) [reply internal/pkg/describe/env.go:1]: Uh, yes! Yipes! Thx.

File: internal/pkg/describe/env_test.go (hunk 4 above)
Comment (huanjani) [reply internal/pkg/describe/env_test.go:201]: Oh, that makes sense. Looks like I don't have to test with/without resources separately--I guess that logic doesn't live in these methods. Thanks!

File: internal/pkg/describe/env_test.go [hunk 5]
```diff
@@ -152,3 +152,126 @@ func TestEnvDescriber_Describe(t *testing.T) {
...
+	}
+	testApp3 := &archer.Application{
+		Project: "testProject",
+		Name:    "testApp3",
+		Type:    "load-balanced",
+	}
+	allApps := []*archer.Application{testApp1, testApp2, testApp3}
+	wantedContent := "{\"environment\":{\"project\":\"testProject\",\"name\":\"testEnv\",\"region\":\"us-west-2\",\"accountID\":\"123456789012\",\"prod\":false,\"registryURL\":\"\",\"executionRoleARN\":\"\",\"managerRoleARN\":\"\"},\"applications\":[{\"project\":\"testProject\",\"name\":\"testApp1\",\"type\":\"load-balanced\"},{\"project\":\"testProject\",\"name\":\"testApp2\",\"type\":\"load-balanced\"},{\"project\":\"testProject\",\"name\":\"testApp3\",\"type\":\"load-balanced\"}],\"tags\":{\"key1\":\"value1\",\"key2\":\"value2\"}}\n"
+
+	t.Run(wantedContent, func(t *testing.T) {
```
Comment (efekarakus) [inline internal/pkg/describe/env_test.go:189]: we don't need to run `t.Run` :) also putting the wantedContent in [t.Run](https://golang.org/pkg/testing/#T.Run) is a bit odd, since the first parameter is supposed to be the name of a subtest
