### PR TITLE
fix(cli): make app init idempotent

### LINKED ISSUE #552: Make "app init" idempotent
### Current Behavior

Running `ecs-preview app init` twice results in the command to fail.

```
$ ecs-preview app init        
Note: It's best to run this command in the root of your workspace.

? Which type of infrastructure pattern best represents your application? Load Balanced Web App

? What do you want to name this Load Balanced Web App? frontend

? Which Dockerfile would you like to use for frontend app? ./Dockerfile
Error: application frontend already exists under project shame-project
```

### Expected Behavior

The CLI should just skip the operation if the resource already exists (locally or remote).
```
Note: It's best to run this command in the root of your workspace.

? Which type of infrastructure pattern best represents your application? Load Balanced Web App

? What do you want to name this Load Balanced Web App? frontend

? Which Dockerfile would you like to use for frontend app? ./Dockerfile

✔ The manifest for frontend app already exist at ecs-project/frontend-app.yml
✔ The ECR repositories for application frontend already exists.

Recommended follow-up actions:
- Update your manifest ecs-project/frontend-app.yml to change the defaults.
- Run `ecs-preview app deploy --name frontend --env test` to deploy your application to a test environment.
```

If a sub-task doesn't exist for whatever reason, then we should create it for example the manifest exists but the repository doesn't:
```
Note: It's best to run this command in the root of your workspace.

? Which type of infrastructure pattern best represents your application? Load Balanced Web App

? What do you want to name this Load Balanced Web App? frontend

? Which Dockerfile would you like to use for frontend app? ./Dockerfile

✔ The manifest for frontend app already exist at ecs-project/frontend-app.yml
⠙ Creating the ECR repositories for application frontend.
```

### PR DESCRIPTION
**Pull request by iamhopaul123**
fix #552.

## Manual test

Suppose we already have created an application named "my-app". Then I run the following command again:

```
$ archer app init
Note: It's best to run this command in the root of your workspace.

? Which type of infrastructure pattern best represents your application? Load Balanced Web App

? What do you want to name this Load Balanced Web App? my-app

? Which Dockerfile would you like to use for my-app? ./Dockerfile

? What port do you want requests from your load balancer forwarded to? 80

✔ Skip writing since the manifest for my-app app already exists at ecs-project/my-app/manifest.yml
Your manifest contains configurations like your container size and ports.

✔ Created ECR repositories for application my-app.
Recommended follow-up actions:
- Update your manifest ecs-project/my-app/manifest.yml to change the defaults.
- Run `ecs-preview app deploy --name my-app --env test` to deploy your application to a test environment.
```
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: internal/pkg/workspace/workspace.go [hunk 1]
```diff
@@ -305,10 +303,17 @@ func (ws *Workspace) write(data []byte, elem ...string) (string, error) {
 	filename := filepath.Join(pathElems...)
 
 	if err := ws.fsUtils.MkdirAll(filepath.Dir(filename), 0755 /* -rwxr-xr-x */); err != nil {
-		return "", fmt.Errorf("failed to create directories for file %s: %w", filename, err)
+		return "", fmt.Errorf("create directories for file %s: %w", filename, err)
+	}
+	exist, err := ws.fsUtils.Exists(filename)
+	if err != nil {
+		return "", fmt.Errorf("check if manifest file exists: %w", err)
```
Comment (efekarakus) [inline internal/pkg/workspace/workspace.go]: nit: can we include the `filename` in the error msg

File: internal/pkg/workspace/workspace.go [hunk 2]
```diff
@@ -305,10 +303,17 @@ func (ws *Workspace) write(data []byte, elem ...string) (string, error) {
...
+	}
+	if exist {
+		return filename, &ErrFileExists{fileName: filename}
```
Comment (efekarakus) [inline internal/pkg/workspace/workspace.go]: What do you think about returning like this:
```suggestion
		return "", &ErrFileExists{Filename: filename}
```
This way we can get rid of the hidden assumption that a user needs to check the first return value if the error is `ErrFileExists` which I don't think is a common practice.

File: internal/pkg/cli/app_init.go [hunk 3]
```diff
@@ -190,18 +181,33 @@ func (o *initAppOpts) createManifest() (string, error) {
...
 	if err != nil {
-		return "", fmt.Errorf("relative path of manifest file: %w", err)
+		return "", fmt.Errorf("get relative path of manifest file: %w", err)
+	}
+
+	log.Infoln()
+	if manifestExist {
+		log.Successf("Skip writing since the manifest for %s app already exists at %s\n", color.HighlightUserInput(o.AppName), color.HighlightResource(relPath))
+	} else {
+		log.Successf("Wrote the manifest for %s app at %s\n", color.HighlightUserInput(o.AppName), color.HighlightResource(relPath))
```
Comment (efekarakus) [inline internal/pkg/cli/app_init.go]: nit:
```go
manifestMsgFmt := "Wrote the manifest for %s app at %s\n"
if manifestExists {
     manifestMsgFmt = "Manifest file for %s app already exists at %s, skipping writing it.\n"
}
log.Successf(manifestMsgFmt, color.HighlightUserInput(o.AppName), color.HighlightResource(relPath))
```
In general, the moment we see an `else` statement that's a hint that we can possibly restructure the code and get rid of it :)

**Comment by efekarakus** [comment]
@Mergifyio refresh
