### PR TITLE
fix: override project name if passed in as a flag

### LINKED ISSUE #570: Project flag value is ignored
## Current Behavior
I have a workspace with a project named "kudos". If I provide a different project name while listing applications it fetches the apps under "kudos" instead of "other".

```bash
$ ecs-preview app ls -p other
Name                Type
--------            ---------------------
frontend            Load Balanced Web App
webhook             Load Balanced Web App
```

## Expected Behavior
```shell
$ ecs-preview app ls -p other 
Error: couldn't find a project named other in account 1111111111 and region us-west-2
```

## Explanation
This is happening because `GlobalOpts` caches the project name from the workspace. If the project name is overwritten, we don't fetch it again from viper.

https://github.com/aws/amazon-ecs-cli-v2/blob/f2a3f0b73e6a106da53da76d0e1bafcf6a26f985/internal/pkg/cli/cli.go#L22-L46

### PR DESCRIPTION
**Pull request by efekarakus**
Fixes #570 

`GlobalOpts` always returned the workspace's project value even if the user set the `--project` flag explicitly.
By setting the `projectName` to the empty string in the constructor of `GlobalOpts`, we force the first `ProjectName()` call to get the latest value from `viper` (the flag's value).

Although this fixes the issue, the fix itself is not obvious and is brittle. 
After I'm done applying the "Validate() -> Ask() -> Execute()" pattern to our commands, it's probably worthwhile looking into removing `GlobalOpts`. Right now it's too difficult as there is no clear place for initialization for our Opts structs.

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

File: internal/pkg/cli/cli.go [hunk 1]
```diff
@@ -30,8 +30,9 @@ func NewGlobalOpts() *GlobalOpts {
 	bindProjectName()
 
 	return &GlobalOpts{
-		projectName: viper.GetString(projectFlag),
-		prompt:      prompt.New(),
+		// Leave the projectName as empty in case it's overwritten by a global flag.
```
Comment (iamhopaul123) [inline internal/pkg/cli/cli.go]: I feel like since now we don't initiate the `opts.projectName` with `opts.ProjectName()`, which means `opts.projectName` and `opts.ProjectName()` they don't necessarily equal to each other, we need to also substitute all usage of `opts.ProjectName()` within `Ask()`, `Validate()`, and `Execute()` to `opts.projectName`. Otherwise if `-p` is set, `opts.ProjectName()` will get expired.

Comment (efekarakus) [reply internal/pkg/cli/cli.go]: I might be misunderstanding the comment 😅, but `opts.projectName` is always equal to `opts.ProjectName()` once `opts.ProjectName()` is invoked (the value is only set within `opts.ProjectName()`).

This change just doesn't set it in the constructor, so it's really the opposite: we want commands to use only `opts.ProjectName()`! 
When an object is created with `opts := NewGlobalOpts()`, the project name should be accessed with `opts.ProjectName()` so that it can grab the latest value from viper. By default the value is the name of the project in the workspace, but if a flag is provided then the value in viper is overwritten.

Let me know if that doesn't make sense, I can update the comments accordingly.

Comment (efekarakus) [reply internal/pkg/cli/cli.go]: I like @sonofachamp's idea of just using `viper` as the repository for our flags, that would allow us to remove this struct.

But that's another refactoring story :P

Comment (iamhopaul123) [reply internal/pkg/cli/cli.go]: I see :+1:

Comment (iamhopaul123) [reply internal/pkg/cli/cli.go]: Yeah, using `viper` directly might be more straightforward
