### PR TITLE
fix: do not error on pipeline init for existing buildspec.yml

### LINKED ISSUE #801: Do not error on pipeline init if buildspec already exists
If buildspec.yml exists from previous pipeline but pipeline was deleted, `pipeline init` will error:

```
Error: write buildspec to workspace: file ~/ecs-project/buildspec.yml already exists
```

Related: https://github.com/aws/amazon-ecs-cli-v2/issues/800

### PR DESCRIPTION
**Pull request by SoManyHs**
Fixes #801

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by SoManyHs** [comment]
With fix:

```
$ archer pipeline init

? Would you like to add an environment to your pipeline? Yes

? Which environment would you like to add to your pipeline? staging

? Would you like to add another environment to your pipeline? Yes

? Which environment would you like to add to your pipeline? hotdog

? Which GitHub repository would you like to use for your application? git@github.com:SoManyHs/aws-reinvent-trivia-2019-backend

? Please enter your GitHub Personal Access Token for your repository: aws-reinvent-trivia-2019-backend [? for help] ****************************************
✔ Created the secret github-token-backend-aws-reinvent-trivia-2019-backend for pipeline source stage!
✔ Buildspec file for project pipeline already exists at , skipping writing it.
✔ Wrote the pipeline manifest for aws-reinvent-trivia-2019-backend at 'pipeline.yml'
The manifest contains configurations for your CodePipeline resources, such as your pipeline stages and build steps.
The buildspec contains the commands to build and push your container images to your ECR repositories.
```

File: internal/pkg/cli/pipeline_init.go [hunk 1]
```diff
@@ -296,9 +295,20 @@ func (o *initPipelineOpts) createBuildspec() (string, error) {
...
+		e, ok := err.(*workspace.ErrFileExists)
+		if !ok {
+			return "", fmt.Errorf("write buildspec to workspace: %w", err)
+		}
+		buildspecExists = true
+		path = e.FileName
+	}
+	buildspecMsgFmt := "Wrote the buildspec for the pipeline's build stage at '%s'\n"
+	if buildspecExists {
+		buildspecMsgFmt = "Buildspec file for project pipeline already exists at %s, skipping writing it.\n"
```
Comment (efekarakus) [inline internal/pkg/cli/pipeline_init.go]: What do you think of `color.Emphasize`-ing "pipeline already exists"? 
https://github.com/aws/amazon-ecs-cli-v2/blob/1e58c0ddbbd61ce1d2890f24f936d0fcf8efbeed/internal/pkg/term/color/color.go#L54-L57

Comment (SoManyHs) [reply internal/pkg/cli/pipeline_init.go]: hmm, we don't do that for the app manifest already exists message, and it seems like we mostly emphasize things that require user input. I could go either way, but I feel like it might be overkill?

File: internal/pkg/cli/pipeline_init.go [hunk 2]
```diff
@@ -296,9 +295,20 @@ func (o *initPipelineOpts) createBuildspec() (string, error) {
 		return "", err
 	}
 	path, err := o.workspace.WritePipelineBuildspec(content)
+	var buildspecExists bool
```
Comment (kohidave) [inline internal/pkg/cli/pipeline_init.go:298]: Slick.
