### PR TITLE
fix(cli): make env init idempotent

### LINKED ISSUE #301: `env init` workflow can't write env SSM entry if user cancels during active deployment
If a user runs `env init` to kick off an active deployment then subsequent `env init` invocations return `✔ Success! Environment test already exists under project myproj! Do nothing.` even if the CloudFormation Stack Status is `CREATE_IN_PROGRESS`.

It might be more clear to the user if we can return a message that informs them when a deployment is already underway for the given inputs, or potentially resumes the progress outputs.

### PR DESCRIPTION
**Pull request by iamhopaul123**
Fix #301, partially addressing #660.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by iamhopaul123** [comment]
## Manual Test

Suppose we already have environment "test" set up and accidentally deleted it from SSM. Then if I run `ecs-preview env init --env test` again, it is supposed to get "test" env registered in SSM store.

```
$ ecs-preview env ls
[no env]
$ ecs-preview env init
? What is your environment's name? test

? Which named profile should we use to create test? default

✔ CloudFormation stack for env test already exists under project my-project! Do nothing.
✔ Linked account 1234567890 and region us-west-2 project my-project.
✔ Created environment test in region us-west-2 under project my-project.
```

Also tested if remove the CFN stack.

File: internal/pkg/store/env.go [hunk 1]
```diff
@@ -37,9 +37,7 @@ func (s *Store) CreateEnvironment(environment *archer.Environment) error {
 		if aerr, ok := err.(awserr.Error); ok {
 			switch aerr.Code() {
 			case ssm.ErrCodeParameterAlreadyExists:
-				return &ErrEnvironmentAlreadyExists{
-					EnvironmentName: environment.Name,
-					ProjectName:     environment.Project}
+				return nil
```
Comment (efekarakus) [inline internal/pkg/store/env.go]: nit: It'd be great if you can also update `CreateProject` to return `nil` that's the only other `Create*` method that doesn't seem to be returning `nil` if this error happens. (can be in a follow-up PR)

File: internal/pkg/store/store_integration_test.go [hunk 2]
```diff
@@ -65,10 +65,6 @@ func Test_SSM_Environment_Integration(t *testing.T) {
 		err = s.CreateEnvironment(&prodEnvironment)
 		require.NoError(t, err)
 
-		// Make sure we can't add a duplicate environment
-		err = s.CreateEnvironment(&prodEnvironment)
-		require.EqualError(t, &store.ErrEnvironmentAlreadyExists{ProjectName: projectToCreate.Name, EnvironmentName: prodEnvironment.Name}, err.Error())
```
Comment (efekarakus) [inline internal/pkg/store/store_integration_test.go]: we could change this to be 
```go
err = s.CreateEnvironment(&prodEnvironment)
require.NoError(t, err)
```

File: internal/pkg/deploy/cloudformation/env.go [hunk 3]
```diff
@@ -65,3 +66,16 @@ func (cf CloudFormation) streamEnvironmentResponse(done chan struct{}, resp chan
...
+	conf := stack.NewEnvStackConfig(&deploy.CreateEnvironmentInput{
+		Project: projectName,
+		Name:    envName,
+	})
+	descr, err := cf.cfnClient.Describe(conf.StackName())
+	if err != nil {
+		return nil, err
+	}
+	return descr.SDK(), nil
+}
```
Comment (efekarakus) [inline internal/pkg/deploy/cloudformation/env.go]: What do you think of changing the follow suggestion instead?

```suggestion
// GetEnvironment returns the Environment metadata from the CloudFormation stack.
func (cf CloudFormation) GetEnvironment(projectName, envName string) (*archer.Environment, error) {
	conf := stack.NewEnvStackConfig(&deploy.CreateEnvironmentInput{
		Project: projectName,
		Name:    envName,
	})
	descr, err := cf.cfnClient.Describe(conf.StackName())
	if err != nil {
		return nil, err
	}
	return conf.ToEnv(descr.SDK())
}
```

Otherwise, now the cli needs to do this work and take an extra dependency on `deploy/cloudformation/stack`.

File: internal/pkg/cli/project_init.go [hunk 4]
```diff
@@ -135,11 +134,7 @@ func (o *initProjectOpts) Execute() error {
 		Domain:    o.DomainName,
 	})
 	if err != nil {
-		// If the project already exists, move on - otherwise return the error.
```
[the remark this answers is not in the document]
Comment (iamhopaul123) [reply internal/pkg/cli/project_init.go]: That's a good question! Never thought about the case when more then one ppl working on the same project. I guess in the scenario you put, when PH want to create a demo project, if they are using the same AWS account, the CLI should do a check first if it exists in the SSM already. This can also be applied to `env init`/`app init`.
