### PR TITLE
fix: app logs scale up issue

### LINKED ISSUE #826: app logs stops updating logs when it gets scaled
I ran `app logs --follow` then the cli keeps updating the latest logs of my application. Then I edited the manifest to change `count` from 1 to 2. After redeploying the application, the old cli session just stopped updating logs, and I had to run `app logs --follow` again so that I can get the latest logs.

### PR DESCRIPTION
**Pull request by iamhopaul123**
fixes #826.

## Manual Test
```$ ecs-preview app logs --follow```
```
...
714beb4 10.0.1.247 - - [09/Apr/2020 18:06:59] "GET / HTTP/1.1" 200 -
714beb4 10.0.0.79 - - [09/Apr/2020 18:06:59] "GET / HTTP/1.1" 200 -
714beb4 10.0.1.247 - - [09/Apr/2020 18:07:09] "GET / HTTP/1.1" 200 -
714beb4 10.0.0.79 - - [09/Apr/2020 18:07:09] "GET / HTTP/1.1" 200 -
714beb4 10.0.1.247 - - [09/Apr/2020 18:07:19] "GET / HTTP/1.1" 200 -
714beb4 10.0.0.79 - - [09/Apr/2020 18:07:19] "GET / HTTP/1.1" 200 -
714beb4 10.0.1.247 - - [09/Apr/2020 18:07:29] "GET / HTTP/1.1" 200 -
714beb4 10.0.0.79 - - [09/Apr/2020 18:07:30] "GET / HTTP/1.1" 200 -
8b2270b  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
8b2270b  * Restarting with stat
8b2270b  * Debugger is active!
8b2270b  * Debugger PIN: 155-519-084
714beb4 10.0.1.247 - - [09/Apr/2020 18:07:39] "GET / HTTP/1.1" 200 -
714beb4 10.0.0.79 - - [09/Apr/2020 18:07:40] "GET / HTTP/1.1" 200 -
714beb4 10.0.1.247 - - [09/Apr/2020 18:07:49] "GET / HTTP/1.1" 200 -
714beb4 10.0.0.79 - - [09/Apr/2020 18:07:50] "GET / HTTP/1.1" 200 -
714beb4 10.0.1.247 - - [09/Apr/2020 18:07:59] "GET / HTTP/1.1" 200 -
714beb4 10.0.0.79 - - [09/Apr/2020 18:08:00] "GET / HTTP/1.1" 200 -
714beb4 10.0.1.247 - - [09/Apr/2020 18:08:09] "GET / HTTP/1.1" 200 -
714beb4 10.0.0.79 - - [09/Apr/2020 18:08:10] "GET / HTTP/1.1" 200 -
714beb4 10.0.1.247 - - [09/Apr/2020 18:08:19] "GET / HTTP/1.1" 200 -
714beb4 10.0.0.79 - - [09/Apr/2020 18:08:20] "GET / HTTP/1.1" 200 -
8b2270b 10.0.0.79 - - [09/Apr/2020 18:08:20] "GET / HTTP/1.1" 200 -
8b2270b 10.0.1.247 - - [09/Apr/2020 18:08:20] "GET / HTTP/1.1" 200 -
...
```

As we can see, when I scaled up the service, `app logs` now is able to detect task `8b2270b` was created and started showing logs for it.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: internal/pkg/aws/cloudwatchlogs/cloudwatchlogs.go [hunk 1]
```diff
@@ -109,11 +108,13 @@ func (s *Service) TaskLogEvents(logGroupName string, streamTokens map[string]*st
 			LogGroupName:  aws.String(logGroupName),
 			LogStreamName: logStreamName,
 			Limit:         aws.Int64(10), // default to be 10
-			NextToken:     streamTokens[*logStreamName],
 		}
 		for _, opt := range opts {
 			opt(in)
 		}
+		if streamLastEventTime[*logStreamName] != 0 {
```
Comment (kohidave) [inline internal/pkg/aws/cloudwatchlogs/cloudwatchlogs.go:115]: Can we add a test for this case plz :D

Comment (iamhopaul123) [reply internal/pkg/aws/cloudwatchlogs/cloudwatchlogs.go:115]: test is coming
