### PR TITLE
Retrieves environments using --json in buildspec

### LINKED ISSUE #417: Generated buildspec failed in the pipeline Build stage
I saw this in the Build stage in the archer pipeline:
```
[Container] 2019/11/19 23:16:56 Running command for env in $envs; do 
  for app in $apps; do 
  ./archer app package -n $app -e $env --output-dir './infrastructure' --tag $tag; 
  done; 
done; 
 
Error: get environment (prod) in project archer-sample-project: ValidationException: Parameter name: can't be prefixed with "ssm" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_ 
    status code: 400, request id: 87205e5b-f26f-4521-8ff6-d5708afdc59f 
```

### PR DESCRIPTION
**Pull request by efekarakus**
Fixes #417 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: internal/pkg/cli/env_list_test.go [hunk 1]
```diff
@@ -23,10 +23,34 @@ func TestEnvList_Execute(t *testing.T) {
...
+					Return(&archer.Project{}, nil)
+				mockEnvStore.
+					EXPECT().
+					ListEnvironments(gomock.Eq("coolproject")).
+					Return([]*archer.Environment{
+						{Name: "test"},
+						{Name: "test2"},
+					}, nil)
+			},
+			expectedContent: `{"environments":[{"project":"","name":"test","region":"","accountID":"","prod":false,"registryURL":"","managerRoleARN":""},{"project":"","name":"test2","region":"","accountID":"","prod":false,"registryURL":"","managerRoleARN":""}]}` + "\n",
```
Comment (hencrice) [inline internal/pkg/cli/env_list_test.go]: should the expected project name be empty?

Comment (efekarakus) [reply internal/pkg/cli/env_list_test.go]: Yeah, because the dummy response from the mock only has a name for the environment and not the project :P
