### PR TITLE
Display the URI for an application after deployment

### LINKED ISSUE #471: Need a URL when I finish deploying
I go through archer init successfully, but then I don't know where my endpoint is.  It just says "Deployed trivia-api:e5f728b to test."  I'm not sure how to get the URL so I can go play with my application (i.e. http://clare-Publi-534J9K0KNAPP-779253318.us-west-2.elb.amazonaws.com)

```
$ archer init
Note: It's best to run this command in the root of your workspace.
Welcome to the ECS CLI! We're going to walk you through some questions 
to help you get set up with a project on ECS. A project is a collection of 
containerized applications (or micro-services) that operate together.

Looks like you don't have any existing projects. Let's create one!
? What would you like to call your project? [? for help] 
Error: prompt for project init: prompt get project name: interrupt
liguori:~/code/demos/trivia-api$ archer init
Note: It's best to run this command in the root of your workspace.
Welcome to the ECS CLI! We're going to walk you through some questions 
to help you get set up with a project on ECS. A project is a collection of 
containerized applications (or micro-services) that operate together.

Looks like you don't have any existing projects. Let's create one!
? What would you like to call your project? clares-demos
? Which type of infrastructure pattern best represents your application? Load Balanced Web App
? What do you want to call this Load Balanced Web App? trivia-api
? Which Dockerfile would you like to use for trivia-api app? ./Dockerfile
Ok great, we'll set up a Load Balanced Web App named trivia-api in project clares-demos.
✔ Created the infrastructure to manage container repositories under project clares-demos.

✔ Wrote the manifest for trivia-api app at 'ecs-project/trivia-api-app.yml'
Your manifest contains configurations like your container size and ports.

✔ Created ECR repositories for application trivia-api.
All right, you're all set for local development.
? Would you like to deploy a staging environment? Yes
✔ Created the infrastructure for the test environment.
- Virtual private cloud on 2 availability zones to hold your services     [Complete]
  - Internet gateway to connect the network to the internet               [Complete]
  - Public subnets for internet facing services                           [Complete]
  - Private subnets for services that can't be reached from the internet  [Complete]
  - Routing tables for services to talk with each other                   [Complete]
- ECS Cluster to hold your services                                       [Complete]
- Application load balancer to distribute traffic                         [Complete]
✔ Linked account 131296546870 and region us-west-2 project clares-demos.
✔ Created environment test in region us-west-2 under project clares-demos.
<snip>
sha256:807de4fe1eff1a1b26c5d6153b45fb4047cf05428efe8a7a61a327ff70430fdd size: 2416
Done!
✔ Deployed trivia-api:e5f728b to test.
```

### PR DESCRIPTION
**Pull request by efekarakus**
Resolves #471 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: internal/pkg/describe/webapp.go [hunk 1]
```diff
@@ -0,0 +1,122 @@
...
+// webAppDescriber retrieves information about a load balanced web application.
+type webAppDescriber struct {
+	*AppDescriber
+	stackDescribers map[string]stackDescriber
+}
+
+func newWebAppDescriber(parent *AppDescriber) *webAppDescriber {
+	return &webAppDescriber{
+		AppDescriber:    parent,
+		stackDescribers: make(map[string]stackDescriber),
```
Comment (sonofachamp) [inline internal/pkg/describe/webapp.go]: It seems like this map would only ever have 0 or 1 value in it. When would that not be the case? Should we just stash the client in an unexported field instead of this map and initialize it if it's uninitialized?

Comment (efekarakus) [reply internal/pkg/describe/webapp.go]: Good point!! I changed things around especially in `describe.go`, so that the same "describer" can be re-used multiple times.
