### PR TITLE
fix: profile selection trims the word "profile" from profile names

### LINKED ISSUE #627: Profile selection trims the word "profile" from profile names
If a user sets up a profile with the word "profile" included we are currently trimming that value which causes the credential chain manager unable to look up the region configuration associated with the profile name:
```
? Which named profile should we use to delete env1? 1
Error: find application cloudformation stacks: MissingRegion: could not find region configuration
```

For example, setting up a profile named `profile1` using `aws configure --profile profile1` gets trimmed down to just `1`:
https://github.com/aws/amazon-ecs-cli-v2/blob/921d12b385e0e7cd3b02f2ba54824a8e415b52c9/internal/pkg/aws/profile/profile.go#L50

We can probably simply replace the `strings.ReplaceAll` with a call to `strings.TrimPrefix` to support profile names with the word "profile" in them.

### PR DESCRIPTION
**Pull request by wingkwong**
c.f.Sections returns the section names. If the profile name contains the word 'profile', it will be replaced by an empty string. 

Example:
```
profile profile1
```

becomes

```
1
```

The change is to use ``strings.TrimPrefix`` instead.
```
profile profile1
```

becomes

```
profile1
```

Fixes #627

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: internal/pkg/aws/profile/profile.go [hunk 1]
```diff
@@ -47,7 +47,7 @@ func (c *Config) Names() []string {
 	var profiles []string
 	for _, section := range c.f.Sections() {
 		// Named profiles created with "aws configure" are formatted as "[profile test]".
-		profiles = append(profiles, strings.TrimSpace(strings.ReplaceAll(section, "profile", "")))
+		profiles = append(profiles, strings.TrimSpace(strings.TrimPrefix(section, "profile")))
```
Comment (efekarakus) [inline internal/pkg/aws/profile/profile.go]: Should we add an extra space at the end of "profile "?
```suggestion
		profiles = append(profiles, strings.TrimSpace(strings.TrimPrefix(section, "profile ")))
```

Comment (efekarakus) [reply internal/pkg/aws/profile/profile.go]: It'd be amazing if we can add a test to make sure "[profile profile1]"  is going to be returned as "profile1" but no worries otherwise!
We can do a fast-follow up with a test file.
