### PR TITLE
fix(app-delete): make app delete more idempotent

### LINKED ISSUE #606: `app delete` errors out when app is not deployed in any env
Currently, `app delete` removes the application entirely, including every env it deploys, SSM store, and local file. However, if an application is not deployed yet, `app delete` fails.

```
$ ecs-preview app delete

? Which application would you like to delete? bad-app

? Are you sure you want to delete bad-app from project david-project? Yes
couldn't find any environments associated with project david-project, try initializing one: `ecs-preview env init`
Error: no environments found
```

I expect `app delete` also removes "bad-app" completely instead of erring out.

### LINKED ISSUE #607: Make "app delete" more idempotent
Currently "app delete" workflow is as follow:

- delete app CFN stack
- delete all images in ECR repo
- remove app specific resources from project CFN stack
- delete SSM param
- delete local files

Ideally we should make all these 5 procedures independent from each other (ie if any of these resources does not exist just continue instead of erring out), so that every time users call `app delete`, they expect the same result (the app is removed entirely). Otherwise it causes issues like #606.

PS if the error occurs because of reasons other than "not exist" then we should error out.

### PR DESCRIPTION
**Pull request by iamhopaul123**
Fixes #607, fixes #606.

Manually tested idempotency for those five steps after this change:

- [x] delete deployed app CFN stacks
- [x] delete all images in ECR repo
- [x] remove app specific resources from project CFN stackset and instance
- [x] delete SSM param
- [x] delete local file

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: internal/pkg/aws/ecr/ecr.go [hunk 1]
```diff
@@ -167,9 +168,30 @@ func (s Service) DeleteImages(images []Image, repoName string) error {
 	return nil
 }
 
+func (s Service) repoExist(repoName string) (bool, error) {
+	_, err := s.ecr.DescribeRepositories(&ecr.DescribeRepositoriesInput{
+		RepositoryNames: aws.StringSlice([]string{repoName}),
+	})
+	if err != nil {
+		aerr := err.(awserr.Error)
+		if aerr.Code() != "RepositoryNotFoundException" {
```
Comment (sonofachamp) [inline internal/pkg/aws/ecr/ecr.go]: Verify the cast succeeded with:
```go
aerr, ok := err.(awserr.Error)
if !ok {
...
```

Otherwise `aerr.Code()` could panic.

Comment (sonofachamp) [inline internal/pkg/aws/ecr/ecr.go]: Should we explicitly handle the scenario where `aerr.Code()` **is equal to** `RepositoryNotFoundException` rather than handling everything that is not? I find the current flow is easy to misread if you're not looking closely.

Comment (iamhopaul123) [reply internal/pkg/aws/ecr/ecr.go]: Thought about that question but I thought the error returns from calling `DescribeRepositories` which should be always expected to return an `awserr`? Anyway there's no downside for adding it so why not.

File: internal/pkg/aws/ecr/ecr.go [hunk 2]
```diff
@@ -167,9 +168,30 @@ func (s Service) DeleteImages(images []Image, repoName string) error {
...
+			return false, err
+		}
+		return false, nil
```
Comment (sonofachamp) [inline internal/pkg/aws/ecr/ecr.go]: Is it safe to return a `nil` error here and say the repo doesn't exist? This seems like a general unhandled error scenario which makes it seem unsafe to assume the repo doesn't exist?

File: internal/pkg/cli/app_delete.go [hunk 3]
```diff
@@ -130,39 +129,14 @@ func (o *deleteAppOpts) askAppName() error {
...
-	if !exists {
-		return fmt.Errorf("input app %s not found", o.AppName)
-	}
-
-	return nil
-}
-
-func (o *deleteAppOpts) retrieveLocalAppName() ([]string, error) {
-	localApps, err := o.workspaceService.Apps()
+func (o *deleteAppOpts) retrieveAppName() ([]string, error) {
```
Comment (sonofachamp) [inline internal/pkg/cli/app_delete.go]: Make the function name plural? `retrieveAppNames()`

File: internal/pkg/cli/app_delete.go [hunk 4]
```diff
@@ -255,9 +219,10 @@ func (o *deleteAppOpts) removeAppProjectResources() error {
 
 	o.spinner.Start(fmt.Sprintf("removing app %s resources from project %s", o.AppName, o.projectName))
 	if err := cfClient.RemoveAppFromProject(proj, o.AppName); err != nil {
-		o.spinner.Stop(log.Serrorf("removing app %s resources from project %s", o.AppName, o.projectName))
-
-		return err
+		if !stackSetNotExistErr(err) {
```
Comment (sonofachamp) [inline internal/pkg/cli/app_delete.go]: I feel like the logic within `stackSetNotExistErr` should be handled inside the `RemoveAppFromProject` logic rather than clients handling that. Maybe return a `nil` error instead of trying to handle this scenario in client code?

File: internal/pkg/cli/app_delete.go [hunk 5]
```diff
@@ -273,6 +238,14 @@ func (o *deleteAppOpts) deleteSSMParam() error {
...
 
 func (o *deleteAppOpts) deleteWorkspaceFile() error {
+	// Return if manifest does not exist.
+	exist, err := o.workspaceService.AppExist(o.AppName)
+	if err != nil {
+		return fmt.Errorf("check if app file %s exists: %w", o.AppName, err)
+	}
+	if !exist {
+		return nil
+	}
```
Comment (sonofachamp) [inline internal/pkg/cli/app_delete.go]: Should we instead update the `DeleteFile` method to handle this scenario? If the file you ask to delete doesn't exist then return a `nil` error?

File: internal/pkg/cli/cli.go [hunk 6]
```diff
@@ -181,3 +184,40 @@ type storeReader interface {
...
+		}
+		if aerr.Code() != "ValidationError" {
+			return stackNotExistErr(errors.Unwrap(err))
+		}
+		if !strings.Contains(aerr.Message(), "does not exist") {
+			return stackNotExistErr(errors.Unwrap(err))
+		}
+		return true
+	}
+}
```
Comment (sonofachamp) [inline internal/pkg/cli/cli.go]: I think the logic for these would be greatly simplified by moving them into the respective lower level packages since the errors wouldn't be wrapped by client code.

File: internal/pkg/cli/app_delete.go (hunk 4 above)
Comment (iamhopaul123) [reply internal/pkg/cli/app_delete.go]: > I feel like the logic within `stackSetNotExistErr` should be handled inside the `RemoveAppFromProject` logic rather than clients handling that. Maybe return a `nil` error instead of trying to handle this scenario in client code?

Agree. Beyond that I think we need to refactoring the `cloudformation` package for the sake of testing, so I am going to work on another PR addressing that after this PR. Before the refactoring I'd rather not putting `stackSetNotExistErr` in it because `RemoveAppFromProject` might change.

File: internal/pkg/cli/env_delete.go [hunk 7]
```diff
@@ -186,6 +186,10 @@ func (o *deleteEnvOpts) askEnvName() error {
 	for _, env := range envs {
 		names = append(names, env.Name)
 	}
+	if len(names) == 0 {
+		return fmt.Errorf("no environment found: run %s first please", color.HighlightCode("env init"))
```
Comment (sonofachamp) [inline internal/pkg/cli/env_delete.go]: Recommending to run `env init` in the context of having run `env delete` feels strange to me.

File: internal/pkg/cli/app_delete.go (hunk 5 above)
Comment (iamhopaul123) [reply internal/pkg/cli/app_delete.go]: I was debating on this. But eventually the reason why I decided to put this out is because I think the workspace package should only be responsible for basic CRUD operation, if we do more than that, it might harm the reusability.

File: internal/pkg/workspace/workspace.go [hunk 8]
```diff
@@ -133,6 +133,29 @@ func (ws *Workspace) writeSummary(projectName string) error {
 	return ws.fsUtils.WriteFile(summaryPath, serializedWorkspaceSummary, 0644)
 }
 
+// AppExist returns if an application exists in the workspace.
+func (ws *Workspace) AppExist(appName string) (bool, error) {
```
Comment (sonofachamp) [inline internal/pkg/workspace/workspace.go]: I feel that this function should be unexported and used internally to this package as part of the `DeleteFile` method as that's the only existing use case right now.

File: internal/pkg/cli/app_delete.go (hunk 5 above)
Comment (sonofachamp) [reply internal/pkg/cli/app_delete.go]: An existence check seems pretty generic to me. If the file doesn't exist you can't delete it. I'd agree with you if it was something potentially inconsistent.

**Comment by sonofachamp** [comment]
Overall looks fine, just some minor things to consider.

File: internal/pkg/aws/ecr/ecr.go (hunk 1 above)
Comment (sonofachamp) [reply internal/pkg/aws/ecr/ecr.go]: Yeah that may be true today, but that could change. The cast check is a good safety measure for that.

File: internal/pkg/cli/cli.go (hunk 6 above)
Comment (iamhopaul123) [reply internal/pkg/cli/cli.go]: Also will address the cloudformation package refactoring in the next PR including adding the missing app delete unit test.

File: internal/pkg/aws/ecr/ecr.go (hunk 1 above)
Comment (iamhopaul123) [reply internal/pkg/aws/ecr/ecr.go]: addressed

File: internal/pkg/aws/ecr/ecr.go (hunk 2 above)
Comment (iamhopaul123) [reply internal/pkg/aws/ecr/ecr.go]: :+1:

File: internal/pkg/cli/app_delete.go (hunk 3 above)
Comment (iamhopaul123) [reply internal/pkg/cli/app_delete.go]: addressed

File: internal/pkg/cli/env_delete.go (hunk 7 above)
Comment (iamhopaul123) [reply internal/pkg/cli/env_delete.go]: addressed

File: internal/pkg/cli/cli.go [hunk 9]
```diff
@@ -181,3 +184,40 @@ type storeReader interface {
...
+
+// returns true if error type is stack not exist.
+func stackNotExistErr(err error) bool {
+	for {
+		if err == nil {
+			return false
+		}
+		aerr, ok := err.(awserr.Error)
+		if !ok {
+			return stackNotExistErr(errors.Unwrap(err))
```
Comment (hencrice) [inline internal/pkg/cli/cli.go]: why do we need recursive calls here? Seems like `Unwrap` itself is already recursive: https://golang.org/src/errors/wrap.go?s=372:400#L4

Same for the `stackSetNotExistErr` above

File: internal/pkg/cli/app_delete.go [hunk 10]
```diff
@@ -174,14 +148,6 @@ func (o *deleteAppOpts) sourceProjectEnvironments() error {
 		return fmt.Errorf("get environments: %w", err)
 	}
 
-	if len(envs) == 0 {
```
[the remark this answers is not in the document]
Comment (iamhopaul123) [reply internal/pkg/cli/app_delete.go]: Suppose you run `app init` and you have ssm store params and local files and you want to delete them. If you have to have at least one env then it will fail. Plus it does not make sense to error out actually: if there's no env then just don't delete application in any env.

File: internal/pkg/cli/app_delete.go [hunk 11]
```diff
@@ -198,7 +164,6 @@ func (o *deleteAppOpts) deleteStacks() error {
 
 		stackName := fmt.Sprintf("%s-%s-%s", o.projectName, env.Name, o.AppName)
 
-		// TODO: check if the stack exists first
```
[the remark this answers is not in the document]
Comment (iamhopaul123) [reply internal/pkg/cli/app_delete.go]: :+1:

File: internal/pkg/cli/app_delete_test.go [hunk 12]
```diff
@@ -270,13 +246,6 @@ func TestDeleteAppOpts_sourceProjectEnvironments(t *testing.T) {
 			want:            fmt.Errorf("get environments: %w", mockError),
 			wantOptsEnvList: nil,
 		},
-		"should return error if call to ListEnvironments() returns an empty list": {
```
[the remark this answers is not in the document]
Comment (iamhopaul123) [reply internal/pkg/cli/app_delete_test.go]: No since we don't error out when there's no env

File: internal/pkg/cli/app_delete.go (hunk 11 above)
[the remark this answers is not in the document]
Comment (iamhopaul123) [reply internal/pkg/cli/app_delete.go]: it's done

[the remark this answers is not in the document]
Comment (iamhopaul123) [reply internal/pkg/cli/app_delete.go]: Sorry about the reply before, I think for this one it is no longer applies because if you don't have existing stack set it won't error out but just skip.

File: internal/pkg/cli/cli.go (hunk 9 above)
Comment (iamhopaul123) [reply internal/pkg/cli/cli.go]: Oh...actually it is not. https://play.golang.org/p/KX468fAuxms

File: internal/pkg/cli/app_delete.go (hunk 5 above)
Comment (iamhopaul123) [reply internal/pkg/cli/app_delete.go]: It would be simpler but it might not be what we want. So what I envision about `delete` is that every time a user run `delete` no matter what the current status they are, they can always completely remove the application. So as for this question, if a user they accidentally delete the local file themselves and they run "app delete" to delete all the other resources, it does not make sense for them to get error saying "error because the file does not exist", since the original purpose for the `delete` command includes deleting the file. They just do things in advance.

However, there's a pitfall for `delete` is we rely too much on SSM store. If users delete parameters from there, there's no way for them to track their apps and delete the rest of those resources.

File: internal/pkg/cli/cli.go [hunk 13]
```diff
@@ -181,3 +184,40 @@ type storeReader interface {
 	archer.ApplicationLister
 	archer.ApplicationGetter
 }
+
+// returns true if error type is stack set not exist.
+func stackSetNotExistErr(err error) bool {
```
Comment (efekarakus) [inline internal/pkg/cli/cli.go]: nit: prefix with `is`
```suggestion
func isStackSetNotExistsErr(err error) bool {
```

File: internal/pkg/cli/env_delete.go [hunk 14]
```diff
@@ -186,6 +186,10 @@ func (o *deleteEnvOpts) askEnvName() error {
 	for _, env := range envs {
 		names = append(names, env.Name)
 	}
+	if len(names) == 0 {
+		return fmt.Errorf("couldn't find any environment in the project %s", o.ProjectName())
+
```
Comment (efekarakus) [inline internal/pkg/cli/env_delete.go]: :+1:

File: internal/pkg/aws/ecr/ecr.go [hunk 15]
```diff
@@ -167,9 +168,33 @@ func (s Service) DeleteImages(images []Image, repoName string) error {
...
 // call to delete all images from the input ECR repository name.
 func (s Service) ClearRepository(repoName string) error {
+	exist, err := s.repoExist(repoName)
+	if err != nil {
+		return fmt.Errorf("check if ecr repo %s exists: %w", repoName, err)
+	}
+	if !exist {
+		return nil
+	}
 	images, err := s.ListImages(repoName)
```
[the remark this answers is not in the document]
Comment (iamhopaul123) [reply internal/pkg/aws/ecr/ecr.go]: :+1:

File: internal/pkg/aws/ecr/ecr.go [hunk 16]
```diff
@@ -194,3 +201,14 @@ func URIFromARN(repositoryARN string) (string, error) {
...
+func isRepoNotFoundErr(err error) (bool, error) {
+	aerr, ok := err.(awserr.Error)
+	if !ok {
+		return false, err
+	}
+	if aerr.Code() == "RepositoryNotFoundException" {
+		return true, nil
+	}
+	return false, err
+}
```
Comment (efekarakus) [inline internal/pkg/aws/ecr/ecr.go]: I believe we can remove the returned error from this function's signature:
```go
func isRepoNotFoundErr(err error) bool {
	aerr, ok := err.(awserr.Error)
	if !ok {
		return false
	} 
	if aerr.Code() == "RepositoryNotFoundException" {
		return true
	}
	return false
}
```
If the err is not an awserr, it's by definition not a RepoNotFound error.
