### PR TITLE
Return owner when Owner() is called

### LINKED ISSUE #298: Return repository owner name when Owner() is called
Previously when Owner() is called, it incorrectly returned the repository name instead of GitHub repo owner name, resulted in incorrect pipeline CFN template.

### PR DESCRIPTION
**Pull request by hencrice**
Previously when Owner() is called, it incorrectly returned the repository name instead of GitHub repo owner name, resulted in incorrect pipeline CFN template.

Closes #298.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: internal/pkg/deploy/deploy.go [hunk 1]
```diff
@@ -160,7 +160,7 @@ func (s *Source) Owner() (string, error) {
 	if err != nil {
 		return "", err
 	}
-	return oAndR.repo, nil
+	return oAndR.owner, nil
```
Comment (efekarakus) [inline internal/pkg/deploy/deploy.go]: Is there a test that'd have caught this?

Comment (hencrice) [reply internal/pkg/deploy/deploy.go]: yep there is an unit test which asserts the expected template output. I didn't check carefully enough when replacing the expected output with the incorrectly-generated output.

Comment (hencrice) [reply internal/pkg/deploy/deploy.go]: yea there's an unit test that compares the generated template against an expected template. I didn't check the generated template carefully enough last time and just copied it over the expected template.
