### PR TITLE
fix(manifest): BackendService port and healthcheck override issue

### LINKED ISSUE #966: [bug] BackendService port and healthcheck values are overwritten if there are environment overrides
It looks like when we're creating a backend service, if we load the environment overrides: 

https://github.com/aws/amazon-ecs-cli-v2/blob/master/internal/pkg/manifest/backend_svc.go#L112-L119

We will always blindly override the port and command. Since the 0 value of port is actually 0, this means that if there are any overrides, the port will be overwritten to be 0 (which is always wrong).

### PR DESCRIPTION
**Pull request by iamhopaul123**
This PR fixes #966 and all (hopefully) related issues concerning our manifest default value and override issues by

1. substitute all fields to pointer value in light of CloudFormation template. After this change all empty value (empty string, 0, false etc.) will be considered as valid value instead of `nil` value;
2. use [mergo](https://github.com/imdario/mergo) package for environment override and remove repetitive and error-prone `copyAndApply` and `deepcopy` methods.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by iamhopaul123** [comment]
e2e tests pass

File: internal/pkg/manifest/backend_svc.go [hunk 1]
```diff
@@ -101,37 +102,38 @@ func (s *BackendService) MarshalBinary() ([]byte, error) {
...
-		TaskConfig: s.TaskConfig.copyAndApply(target.TaskConfig),
-		Sidecar:    s.Sidecar.copyAndApply(target.Sidecar),
-		LogConfig:  s.LogConfig.copyAndApply(target.LogConfig),
+	target := BackendService{
+		Image:      overrideConfig.Image,
+		TaskConfig: overrideConfig.TaskConfig,
+		LogConfig:  overrideConfig.LogConfig,
+		Sidecar:    overrideConfig.Sidecar,
+	}
+	if err := mergo.Merge(&s, target, mergo.WithOverride, mergo.WithOverwriteWithEmptyValue); err != nil {
```
Comment (efekarakus) [inline internal/pkg/manifest/backend_svc.go:121]: I wonder if once target is merged it will leave the original `*s` to be the same as before the overrides.

Can we add a test for that, say that we have the default value set to `cpu=256` and add an env override with `cpu=512`. Besides checking that the output is `512` can we check if the original remains `256`?

File: internal/pkg/manifest/lb_web_svc.go [hunk 2]
```diff
@@ -112,23 +100,26 @@ func (s *LoadBalancedWebService) MarshalBinary() ([]byte, error) {
...
-		Sidecar:     s.Sidecar.copyAndApply(target.Sidecar),
-		LogConfig:   s.LogConfig.copyAndApply(target.LogConfig),
+	target := LoadBalancedWebService{
+		Image:       overrideConfig.Image,
+		RoutingRule: overrideConfig.RoutingRule,
+		TaskConfig:  overrideConfig.TaskConfig,
+		LogConfig:   overrideConfig.LogConfig,
+		Sidecar:     overrideConfig.Sidecar,
+	}
+	if err := mergo.Merge(&s, target, mergo.WithOverride, mergo.WithOverwriteWithEmptyValue); err != nil {
```
Comment (efekarakus) [inline internal/pkg/manifest/lb_web_svc.go:120]: [`mergo.WithOverwriteWithEmptyValue`](https://github.com/imdario/mergo/blob/9080aaff85364c8348d7086f09cca7f803e14822/merge.go#L310-L314) is a superset of `mergo.WithOverride`. We can remove the latter

File: internal/pkg/manifest/svc.go [hunk 3]
```diff
@@ -27,197 +27,57 @@ var ServiceTypes = []string{
...
 }
 
 type destinationConfig struct {
-	Name           string  `yaml:"name"`
+	Name           *string `yaml:"name"`
 	IncludePattern *string `yaml:"includePattern"` // can be empty string as a valid value
 	ExcludePattern *string `yaml:"excludePattern"`
 }
 
-func (lc LogConfig) copyAndApply(other LogConfig) LogConfig {
```
Comment (efekarakus) [inline internal/pkg/manifest/svc.go:60]: 😂 yess

File: internal/pkg/manifest/backend_svc.go [hunk 4]
```diff
@@ -101,37 +102,38 @@ func (s *BackendService) MarshalBinary() ([]byte, error) {
...
 func (s *BackendService) DockerfilePath() string {
-	return s.Image.Build
+	return aws.StringValue(s.Image.Build)
 }
 
 // ApplyEnv returns the service manifest with environment overrides.
 // If the environment passed in does not have any overrides then it returns itself.
-func (s *BackendService) ApplyEnv(envName string) *BackendService {
-	target, ok := s.Environments[envName]
+func (s BackendService) ApplyEnv(envName string) (*BackendService, error) {
```
[the remark this answers is not in the document]
Comment (iamhopaul123) [reply internal/pkg/manifest/backend_svc.go:110]: I think I changed this simply to avoid this method from accidentally change the receiver `BackendService` since this method should only use the receiver to create another overrided `BackendService`.

File: internal/pkg/manifest/backend_svc.go (hunk 1 above)
Comment (iamhopaul123) [reply internal/pkg/manifest/backend_svc.go:121]: The original `s` won't change since I don't use a pointer of `BackendService` as the receiver. But yeah for safe i'll add a test for that.

File: internal/pkg/manifest/lb_web_svc.go (hunk 2 above)
Comment (iamhopaul123) [reply internal/pkg/manifest/lb_web_svc.go:120]: it's not :| I tried to remove that one and the unit test failed because it was not overriden

File: internal/pkg/manifest/backend_svc.go (hunk 1 above)
Comment (iamhopaul123) [reply internal/pkg/manifest/backend_svc.go:121]: Added!

File: internal/pkg/manifest/backend_svc.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (efekarakus) [reply internal/pkg/manifest/backend_svc.go:110]: It's probably fine to keep it as a value receiver. I'm not certain but my guess is for consistency, so that if a client initializes a `BackendService` by value they will only be able to use the `ApplyEnv` method, whereas if it's a pointer they'll be able to use everything. Ideally, once you initialize you should see everything I think 🤔

[the remark this answers is not in the document]
Comment (iamhopaul123) [reply internal/pkg/manifest/backend_svc.go:110]: > so that if a client initializes a BackendService by value they will only be able to use the ApplyEnv method

This is confusing but true 🤦‍♂️
