### PR TITLE
Change -d validation to check Dockerfile for "app init"

### LINKED ISSUE #533: Error: read directory with `-d` flag value in `init` workflow
Including `Dockerfile` in the `-d` flag path results in an error from calling the `listDockerfiles` function.

Some potential options to fix:
* Update the `listDockerfiles` function to check if the input `dir` parameter is indeed a directory before calling `ReadDir`
* Make an `os.Stat` call on the input flag value [before calling `listDockerfiles`] to see if the file exists and error out if it doesn't

```
$ ecs-preview init -a myapp -p myproj -d ./Dockerfile --deploy -t "Load Balanced Web App"
Note: It's best to run this command in the root of your Git repository.
Welcome to the ECS CLI! We're going to walk you through some questions 
to help you get set up with a project on ECS. A project is a collection of 
containerized applications (or micro-services) that operate together.

Error: read directory: readdirent: not a directory
$
```

### PR DESCRIPTION
**Pull request by iamhopaul123**
Fix #533. I think it would be confusing if we allow "-d" flag to accept either "path to the directory that containers Dockerfile" or "path to Dockerfile". Make more sense to allow only "path to Dockerfile" using "-d" flag.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: internal/pkg/cli/app_init.go [hunk 1]
```diff
@@ -83,9 +83,12 @@ func (opts *InitAppOpts) Validate() error {
 		}
 	}
 	if opts.DockerfilePath != "" {
-		if _, err := listDockerfiles(opts.fs, opts.DockerfilePath); err != nil {
+		if _, err := opts.fs.Stat(opts.DockerfilePath); err != nil {
 			return err
 		}
+		if !strings.HasSuffix(opts.DockerfilePath, "/Dockerfile") {
+			return fmt.Errorf("a valid Dockerfile path is required")
+		}
```
Comment (sonofachamp) [inline internal/pkg/cli/app_init.go]: Should we validate the suffix before going to the filesystem?

Comment (iamhopaul123) [reply internal/pkg/cli/app_init.go]: Yeah thought about that question, but can't figure out which comes first will be better. Do you have any idea why we should validate suffix first?

Comment (sonofachamp) [reply internal/pkg/cli/app_init.go]: Ultimately don't think it's a big deal, but would prefer to do a value sanity check first. If the input value isn't something we support then there's no point in searching the file system for it I think.

File: internal/pkg/cli/app_init.go [hunk 2]
```diff
@@ -83,7 +83,10 @@ func (opts *InitAppOpts) Validate() error {
 		}
 	}
 	if opts.DockerfilePath != "" {
-		if _, err := listDockerfiles(opts.fs, opts.DockerfilePath); err != nil {
+		if !strings.HasSuffix(opts.DockerfilePath, "/Dockerfile") {
```
Comment (efekarakus) [inline internal/pkg/cli/app_init.go]: What do you think about only checking if the path is a directory and erroring out then? If it's a file we just pass.

Right now, I think there can be two things that are problematic. 
1. Users can have Dockerfiles that don't end with "Dockerfile" (https://docs.docker.com/engine/reference/commandline/build/#specify-a-dockerfile--f) so we should be able to handle those.
2. I'm not sure if this would work with windows because of the forward slash.

Comment (efekarakus) [reply internal/pkg/cli/app_init.go]: Oh and can we update the flag description to "Path to the Dockerfile." instead of "Path to the directory with Dockerfile."

Comment (iamhopaul123) [reply internal/pkg/cli/app_init.go]: :+1: Addressed

File: internal/pkg/cli/app_init.go [hunk 3]
```diff
@@ -83,9 +83,13 @@ func (opts *InitAppOpts) Validate() error {
 		}
 	}
 	if opts.DockerfilePath != "" {
-		if _, err := listDockerfiles(opts.fs, opts.DockerfilePath); err != nil {
+		isDir, err := afero.IsDir(opts.fs, opts.DockerfilePath)
+		if err != nil {
 			return err
 		}
+		if isDir {
+			return fmt.Errorf("dockerfile path expected, got %s", opts.DockerfilePath)
```
Comment (efekarakus) [inline internal/pkg/cli/app_init.go]: nit: This error message doesn't mention that the path is a directory, maybe "Dockerfile path is a directory:%s, please provide path to file."
