### PR TITLE
fix(describe): filter apps to show only those specific to env

### LINKED ISSUE #864: env show execute--filter apps
Currently, apps being listed by env show are all of the ones under a project, not the ones specific to the selected environment. Apps should be filtered much like app show filters environments, but in Describe() rather than RetrieveData().

### PR DESCRIPTION
**Pull request by huanjani**
Fixes #864.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: internal/pkg/describe/env.go [hunk 1]
```diff
@@ -50,23 +60,58 @@ func NewEnvDescriber(projectName string, envName string) (*EnvDescriber, error)
...
+		stackDesc, err := e.cloudformation.Describe(singleStack)
+		if err != nil {
+			return nil, err
+		}
+		params := make(map[string]string)
+		for _, param := range stackDesc.Parameters {
+			params[*param.ParameterKey] = *param.ParameterValue
+		}
+		appName := params["AppName"]
+		for _, app := range e.apps {
```
Comment (iamhopaul123) [inline internal/pkg/describe/env.go:106]: Why do we need to do this :P We can prob just include those deployed app name if we include `"ecs-project": e.env.Project` when searching for resources.

File: internal/pkg/describe/env.go [hunk 2]
```diff
@@ -11,11 +11,17 @@ import (
...
 	"github.com/aws/amazon-ecs-cli-v2/internal/pkg/aws/session"
 	"github.com/aws/amazon-ecs-cli-v2/internal/pkg/store"
 	sess "github.com/aws/aws-sdk-go/aws/session"
 )
 
+const (
+	cloudformationResourceType = "AWS::CloudFormation::Stack"
+)
+
 type EnvDescription struct {
```
[the remark this answers is not in the document]
Comment (huanjani) [reply internal/pkg/describe/env.go:25]: Yup. Thanks!

File: internal/pkg/describe/env.go [hunk 3]
```diff
@@ -50,23 +60,58 @@ func NewEnvDescriber(projectName string, envName string) (*EnvDescriber, error)
...
 	return &EnvDescriber{
-		env:          env,
-		store:        svc,
-		apps:         apps,
-		sessProvider: sess,
+		env:            env,
+		store:          svc,
+		proj:           proj,
+		apps:           apps,
+		sessProvider:   sess,
```
[the remark this answers is not in the document]
Comment (huanjani) [reply internal/pkg/describe/env.go:67]: You're right. Deleting. Thanks!

File: internal/pkg/describe/env.go [hunk 4]
```diff
@@ -50,23 +60,58 @@ func NewEnvDescriber(projectName string, envName string) (*EnvDescriber, error)
...
+	if err != nil {
+		return nil, err
+	}
+
 	return &EnvDescription{
 		Environment:  e.env,
-		Applications: e.apps,
-		Tags:         tags,
+		Applications: appsForEnv,
+		Tags:         e.proj.Tags,
```
[the remark this answers is not in the document]
Comment (huanjani) [reply internal/pkg/describe/env.go:83]: I will display them in human output. Thank you for the reminder. The tags will be coming from two different sources. Here, these are the ones manually added by the user and stored in SSM for the project. Next, I will add the ones from the CFN stack.

File: internal/pkg/describe/env.go (hunk 1 above)
Comment (huanjani) [reply internal/pkg/describe/env.go:106]: I was trying to get archer.Application objects from the stack strings returned by `GetResourcesByTags`. How do I more efficiently extract the app name from the stack string and convert it into the app object (so we can access the fields Name and Type for output)? Thanks!

**Comment by huanjani** [comment]
manual output:
```
$ ecs-preview env show

? Which project's environments would you like to show? dinder

? Which environment of dinder would you like to show? another-env
About

  Name              another-env
  Production        false
  Region            us-west-2
  Account ID        327148513104

Applications

  Name              Type
  second-api        Load Balanced Web App
$ 
```

File: internal/pkg/describe/env.go (hunk 1 above)
Comment (iamhopaul123) [reply internal/pkg/describe/env.go:106]: Oh I got you. Then it makes sense to me.

File: internal/pkg/describe/env.go [hunk 5]
```diff
@@ -50,23 +60,58 @@ func NewEnvDescriber(projectName string, envName string) (*EnvDescriber, error)
...
 	}, nil
 }
 
+func (e *EnvDescriber) FilterAppsForEnv() ([]*archer.Application, error) {
+	var appObjects []*archer.Application
+	tags := map[string]string{
+		"ecs-environment": e.env.Name,
```
[the remark this answers is not in the document]
Comment (huanjani) [reply internal/pkg/describe/env.go:94]: > Would be better to use the tag consts defined in `stack` pkg.

GetResourcesByTags is expecting a map of strings: strings. Can I use tag consts--aren't those Tag objects?

[the remark this answers is not in the document]
Comment (iamhopaul123) [reply internal/pkg/describe/env.go:94]: maybe stack.EnvTagKey for "ecs-environment"

File: internal/pkg/describe/env.go [hunk 6]
```diff
@@ -25,10 +35,13 @@ type EnvDescription struct {
...
 	env  *archer.Environment
+	proj *archer.Project
 	apps []*archer.Application
 
-	store        storeSvc
-	sessProvider *sess.Session
+	store          storeSvc
+	sessProvider   *sess.Session
+	rgClient       resourcegroups.ResourceGroupsClient
+	cloudformation *cloudformation.CloudFormation
```
Comment (iamhopaul123) [inline internal/pkg/describe/env.go:44]: Seems like `sessProvider` and `cloudformation` are defined but not used?

File: internal/pkg/describe/env.go [hunk 7]
```diff
@@ -50,23 +64,70 @@ func NewEnvDescriber(projectName string, envName string) (*EnvDescriber, error)
...
+
+	tags := map[string]string{
+		"ecs-environment": e.env.Name,
+	}
+	arns, err := e.rgClient.GetResourcesByTags(cloudformationResourceType, tags)
+	if err != nil {
+		return nil, err
+	}
+
+	var stacksOfEnvironment []string
```
Comment (iamhopaul123) [inline internal/pkg/describe/env.go:101]: What do you think maybe like this?

``` go
...
        stacksofEnvironment := make(map[string]bool)
	for _, arn := range arns {
		stack, err := e.parseARN(arn)
		if err != nil {
			return nil, err
		}
		stacksOfEnvironment[stack] = true
	}
        
	for _, app := range e.apps {
		stackName := stack.NameForApp(e.proj.Name, e.env.Name, app.Name)
		if  stacksOfEnvironment[stackName] {
				appObjects = append(appObjects, app)
                }
	}
...
```

File: internal/pkg/describe/env.go [hunk 8]
```diff
@@ -50,23 +64,70 @@ func NewEnvDescriber(projectName string, envName string) (*EnvDescriber, error)
...
+		}
+	}
+
+	return appObjects, nil
+}
+
+func (e *EnvDescriber) parseARN(resourceArn string) (string, error) {
+	parsedArn, err := arn.Parse(resourceArn)
+	if err != nil {
+		return "", fmt.Errorf("parse ARN: #{resourceArn}")
```
Comment (iamhopaul123) [inline internal/pkg/describe/env.go:125]: What's this error handling :P

File: internal/pkg/describe/env.go [hunk 9]
```diff
@@ -50,23 +64,70 @@ func NewEnvDescriber(projectName string, envName string) (*EnvDescriber, error)
...
+			if stack == stackName {
+				appObjects = append(appObjects, app)
+			}
+		}
+	}
+
+	return appObjects, nil
+}
+
+func (e *EnvDescriber) parseARN(resourceArn string) (string, error) {
```
Comment (iamhopaul123) [inline internal/pkg/describe/env.go:122]: what do you think moving this function to `resourcegroups` pkg so that it can be reused to parse the arn to get the stack name?

Ideally `GetResourcesByTags` can return a `resourceArn` type that has `stackName()` method that returns the stack name.

File: internal/pkg/describe/env.go [hunk 10]
```diff
@@ -50,23 +64,70 @@ func NewEnvDescriber(projectName string, envName string) (*EnvDescriber, error)
...
+	parsedArn, err := arn.Parse(resourceArn)
+	if err != nil {
+		return "", fmt.Errorf("parse ARN: #{resourceArn}")
+	}
+	stack := strings.Split(parsedArn.Resource, "/")
+	return stack[1], nil
```
Comment (iamhopaul123) [inline internal/pkg/describe/env.go:128]: Potential "index out of range" panic.

File: internal/pkg/describe/env.go [hunk 11]
```diff
@@ -50,23 +64,70 @@ func NewEnvDescriber(projectName string, envName string) (*EnvDescriber, error)
...
+	for _, arn := range arns {
+		stack, err := e.parseARN(arn)
+		if err != nil {
+			return nil, err
+		}
+		stacksOfEnvironment = append(stacksOfEnvironment, stack)
+	}
+
+	for _, app := range e.apps {
+		stackName := stack.NameForApp(e.proj.Name, e.env.Name, app.Name)
```
Comment (iamhopaul123) [inline internal/pkg/describe/env.go:111]: nice!

File: internal/pkg/describe/env.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (huanjani) [reply internal/pkg/describe/env.go:94]: Ah, I get it now. Thank you!

File: internal/pkg/describe/env.go (hunk 6 above)
Comment (huanjani) [reply internal/pkg/describe/env.go:44]: Ah, right--now that I took out the CFN Describe method. Thx!

File: internal/pkg/describe/env.go (hunk 7 above)
Comment (huanjani) [reply internal/pkg/describe/env.go:101]: Ah, I see. That avoids the nested for loops. Much better! Thanks!

File: internal/pkg/describe/env.go (hunk 10 above)
Comment (huanjani) [reply internal/pkg/describe/env.go:128]: Thanks. Added a length check/return.

File: internal/pkg/describe/env.go (hunk 9 above)
Comment (huanjani) [reply internal/pkg/describe/env.go:114]: Right now, cloudwatch has getAlarmName and codepipeline has getPipelineName that also call arn.Parse but these all do slightly different things with what's returned. Should I leave this here until GetResourcesByTags returns a `resourceArn` type and then we can move all of these parsing functions into `resourceGroups`? In the meantime, I'll rename this one to match the above.

Comment (iamhopaul123) [reply internal/pkg/describe/env.go]: don't worry about that. Don't need to do that in this PR.

File: internal/pkg/describe/env.go [hunk 12]
```diff
@@ -50,23 +64,69 @@ func NewEnvDescriber(projectName string, envName string) (*EnvDescriber, error)
...
 	return &EnvDescription{
 		Environment:  e.env,
-		Applications: e.apps,
-		Tags:         tags,
+		Applications: appsForEnv,
+		Tags:         e.proj.Tags,
 	}, nil
 }
 
+func (e *EnvDescriber) FilterAppsForEnv() ([]*archer.Application, error) {
```
Comment (SoManyHs) [inline internal/pkg/describe/env.go:89]: Does this need to be exported? If so, please include a doc string!

File: internal/pkg/describe/env_test.go [hunk 13]
```diff
@@ -38,43 +43,47 @@ func TestEnvDescriber_FilterAppsForEnv(t *testing.T) {
 	}
 	testApp1 := &archer.Application{
 		Project: "testProject",
-		Name: "testApp1",
-		Type: "load-balanced",
+		Name:    "testApp1",
+		Type:    "load-balanced",
 	}
-	testApp3 :=	&archer.Application{
+	testApp3 := &archer.Application{
```
Comment (SoManyHs) [inline internal/pkg/describe/env_test.go:49]: nit: am I missing something, or is there not a testApp2?

File: internal/pkg/describe/env_test.go [hunk 14]
```diff
@@ -38,43 +43,47 @@ func TestEnvDescriber_FilterAppsForEnv(t *testing.T) {
...
-		proj *archer.Project
-		apps []*archer.Application
+		//env  *archer.Environment
+		//proj *archer.Project
+		//apps []*archer.Application
 
-		setupMocks func(mocks envDescriberMocks)
-		mockrgClient	func(m *mocks.MockresourceGroupsClient)
+		setupMocks   func(mocks envDescriberMocks)
+		mockrgClient func(m *mocks.MockresourceGroupsClient)
```
Comment (SoManyHs) [inline internal/pkg/describe/env_test.go:64]: Looks like you have a `mockResourceGroupsClient` already defined in your `envDescriberMocks` struct [here](https://github.com/aws/amazon-ecs-cli-v2/pull/900/commits/b4de504ee910c104f1174e1f9ad2ded0862b5c4b#diff-6a7ac9331b26ee29d1305016737c4442L17), so we probably don't need `mockrgClient` here as a separate field in the test case, no?

File: internal/pkg/describe/env_test.go [hunk 15]
```diff
@@ -38,43 +43,47 @@ func TestEnvDescriber_FilterAppsForEnv(t *testing.T) {
...
-
-
+			wantedError: fmt.Errorf("get ARN: some error"),
 		},
-		"return error if fail to get stack name from ARN": {
-
-		},
-		"successfully return correct apps for env": {
-
+		"successfully return appropriate app objects": {
```
Comment (SoManyHs) [inline internal/pkg/describe/env_test.go:77]: nit: maybe "successfully returns apps in the given env" or something like that?

File: internal/pkg/describe/env_test.go [hunk 16]
```diff
@@ -38,43 +43,47 @@ func TestEnvDescriber_FilterAppsForEnv(t *testing.T) {
...
-		setupMocks func(mocks envDescriberMocks)
-		mockrgClient	func(m *mocks.MockresourceGroupsClient)
+		setupMocks   func(mocks envDescriberMocks)
+		mockrgClient func(m *mocks.MockresourceGroupsClient)
 
-		wantedApps   []*archer.Application
+		wantedApps  []*archer.Application
 		wantedError error
 	}{
 		"return error if fail to get ARN": {
```
Comment (SoManyHs) [inline internal/pkg/describe/env_test.go:69]: nit: perhaps more descriptive to say something like "errors if cannot retrieve resource ARNS by tags" ?

File: internal/pkg/describe/env_test.go [hunk 17]
```diff
@@ -4,24 +4,29 @@
...
 	mockResourceGroupsClient *mocks.MockresourceGroupsClient
 }
 
 func TestEnvDescriber_FilterAppsForEnv(t *testing.T) {
 	const (
-		badParsedStack  = "badMockArn"
-		testParsedStack1 = "phonetool-test-app1"
-		testParsedStack2 = "phonetool-prod-app2"
+		testARN1         = "arn:aws:cloudformation:us-west-2:123456789012:stack/testProject-testEnv1-testApp1/6d75d1g0-8b1a-11ea-b358-06c1882c17fd"
+		testARN2         = "arn:aws:cloudformation:us-west-2:123456789012:stack/testProject-testEnv1-testApp3/7d75d1f0-8c1a-11ea-b358-06c1882c17fc"
```
Comment (SoManyHs) [inline internal/pkg/describe/env_test.go:26]: nit: it's a little confusing to have this const be called `testARN2` but the app name `testApp3` -- it's not a big deal but does add a bit more cognitive load.

File: internal/pkg/describe/env_test.go [hunk 18]
```diff
@@ -4,24 +4,29 @@
...
 	"github.com/aws/amazon-ecs-cli-v2/internal/pkg/deploy/cloudformation/stack"
 	"github.com/aws/amazon-ecs-cli-v2/internal/pkg/describe/mocks"
 	"github.com/golang/mock/gomock"
 	"github.com/stretchr/testify/require"
-	"testing"
 )
 
 type envDescriberMocks struct {
-	mockStoreService   *mocks.MockstoreSvc
+	mockStoreService         *mocks.MockstoreSvc
```
Comment (SoManyHs) [inline internal/pkg/describe/env_test.go:19]: Do we actually need the `mockStoreService` for these tests? It looks like we don't call anything on the store for the `Describe()` method, so I would probably leave this out for now (which means you don't need it in lines 99 and 110)

I'm not sure if you'll need to mock the store for other things you might want to test in the describer -- I do like to have the `fooMocks` struct generally mirror the `Foo` thing you're mocking (in this case, "foo" == `EnvDescriber`) so that instantiating it in the test is as close to the actual constructor as possible, but if it's not used in a particular set of unit tests I might leave it out.

Comment (huanjani) [reply internal/pkg/describe/env_test.go:19]: I had taken this out yesterday, on your advice, but have since put it back in because I am now back to writing tests for Describe, as I have changed FilterAppsForEnv to filterAppsForEnv.

File: internal/pkg/describe/env.go (hunk 12 above)
Comment (huanjani) [reply internal/pkg/describe/env.go:91]: No, changing to lowercase/non-export. Thanks!

File: internal/pkg/describe/env.go [hunk 19]
```diff
@@ -50,23 +65,68 @@ func NewEnvDescriber(projectName string, envName string) (*EnvDescriber, error)
...
+	arns, err := e.rgClient.GetResourcesByTags(cloudformationResourceType, tags)
+	if err != nil {
+		return nil, fmt.Errorf("get resources for env %s: %w", e.env.Name, err)
+	}
+
+	stacksOfEnvironment := make(map[string]bool)
+	for _, arn := range arns {
+		stack, err := e.getStackName(arn)
+		if err != nil {
+			return nil, fmt.Errorf("get stack name from arn %s: %w", arn, err)
```
Comment (iamhopaul123) [inline internal/pkg/describe/env.go:105]: nit: ARN for consistency.

File: internal/pkg/describe/env.go [hunk 20]
```diff
@@ -50,23 +65,68 @@ func NewEnvDescriber(projectName string, envName string) (*EnvDescriber, error)
...
+	if err != nil {
+		return nil, err
+	}
+
 	return &EnvDescription{
 		Environment:  e.env,
-		Applications: e.apps,
-		Tags:         tags,
+		Applications: appsForEnv,
+		Tags:         e.proj.Tags,
```
Comment (iamhopaul123) [inline internal/pkg/describe/env.go:86]: I thought `Tags` field should be tags for the environment stack instead of project's tags? What tags do we want to show in `env show`?

File: internal/pkg/describe/env_test.go [hunk 21]
```diff
@@ -2,3 +2,142 @@
...
+		"error if GetResourcesByTags fails": {
+			setupMocks: func(m envDescriberMocks) {
+				gomock.InOrder(
+					m.mockResourceGroupsClient.EXPECT().GetResourcesByTags(cloudformationResourceType, rgTags).
+						Return(nil, mockError),
+				)
+			},
+			wantedError: fmt.Errorf("get resources for env testEnv: some error"),
+		},
+		"error if getStackName fails because cannot parse resourceARN": {
```
[the remark this answers is not in the document]
Comment (huanjani) [reply internal/pkg/describe/env_test.go:80]: Oh--I thought you said I didn't need to test that one because it's a member function (SDK)?? Happy to do it, though!

File: internal/pkg/describe/env.go (hunk 20 above)
Comment (huanjani) [reply internal/pkg/describe/env.go:86]: We will show both. I am adding the tags from the environment stack next! :)

File: internal/pkg/describe/env_test.go (hunk 21 above)
[the remark this answers is not in the document]
Comment (iamhopaul123) [reply internal/pkg/describe/env_test.go:80]: Sorry for the confusion 😅we are not testing SDK but our input for the SDK function might be invalid.

[the remark this answers is not in the document]
Comment (huanjani) [reply internal/pkg/describe/env_test.go:80]: Ahh, I get it now. Thanks. Will do!

File: internal/pkg/describe/env.go [hunk 22]
```diff
@@ -50,23 +65,68 @@ func NewEnvDescriber(projectName string, envName string) (*EnvDescriber, error)
...
 	}, nil
 }
 
+func (e *EnvDescriber) filterAppsForEnv() ([]*archer.Application, error) {
+	var appObjects []*archer.Application
```
Comment (efekarakus) [inline internal/pkg/describe/env.go:91]: nit:
```suggestion
	var apps []*archer.Application
```

Comment (efekarakus) [reply internal/pkg/describe/env.go:91]: Would you mind declaring this variable closer to where it's used? (above the for-loop at l. 109) It just makes it a bit easier for the reader to track how it's used.
https://wiki.c2.com/?DeclareVariablesAtFirstUse

File: internal/pkg/describe/env.go [hunk 23]
```diff
@@ -50,23 +65,68 @@ func NewEnvDescriber(projectName string, envName string) (*EnvDescriber, error)
...
+
+	tags := map[string]string{
+		stack.EnvTagKey: e.env.Name,
+	}
+	arns, err := e.rgClient.GetResourcesByTags(cloudformationResourceType, tags)
+	if err != nil {
+		return nil, fmt.Errorf("get resources for env %s: %w", e.env.Name, err)
```
Comment (efekarakus) [inline internal/pkg/describe/env.go:98]:
```suggestion
		return nil, fmt.Errorf("get %s resources for env %s: %w", cloudformationResourceType, e.env.Name, err)
```

File: internal/pkg/describe/env.go [hunk 24]
```diff
@@ -50,23 +65,68 @@ func NewEnvDescriber(projectName string, envName string) (*EnvDescriber, error)
...
+	}
+
+	stacksOfEnvironment := make(map[string]bool)
+	for _, arn := range arns {
+		stack, err := e.getStackName(arn)
+		if err != nil {
+			return nil, fmt.Errorf("get stack name from ARN %s: %w", arn, err)
```
Comment (efekarakus) [inline internal/pkg/describe/env.go:105]:
```suggestion
			return nil, err
```
We don't need to add extra context if the error is returned from a private method (the info is redundant). Instead, usually the only time we want to wrap errors is if it's returned from a public method
https://www.efekarakus.com/golang/2019/09/26/when-to-wrap-errors.html

File: internal/pkg/describe/env.go [hunk 25]
```diff
@@ -50,23 +65,68 @@ func NewEnvDescriber(projectName string, envName string) (*EnvDescriber, error)
...
+
+	tags := map[string]string{
+		stack.EnvTagKey: e.env.Name,
+	}
+	arns, err := e.rgClient.GetResourcesByTags(cloudformationResourceType, tags)
+	if err != nil {
+		return nil, fmt.Errorf("get resources for env %s: %w", e.env.Name, err)
+	}
+
+	stacksOfEnvironment := make(map[string]bool)
```
Comment (efekarakus) [inline internal/pkg/describe/env.go:101]: dumb question :P why is this a map? couldn't we append to a slice instead?

File: internal/pkg/describe/env.go [hunk 26]
```diff
@@ -50,23 +65,68 @@ func NewEnvDescriber(projectName string, envName string) (*EnvDescriber, error)
...
+}
+
+func (e *EnvDescriber) getStackName(resourceArn string) (string, error) {
+	parsedArn, err := arn.Parse(resourceArn)
+	if err != nil {
+		return "", fmt.Errorf("parse ARN %s: %w", resourceArn, err)
+	}
+	stack := strings.Split(parsedArn.Resource, "/")
+	if len(stack) < 2 {
+		return "", fmt.Errorf("cannot parse ARN resource %s", parsedArn.Resource)
```
Comment (efekarakus) [inline internal/pkg/describe/env.go:125]: nit: 
> When adding context to returned errors, keep the context succinct by avoiding phrases like "failed to", which state the obvious and pile up as the error percolates up through the stack

https://github.com/uber-go/guide/blob/master/style.md#error-wrapping

We've been trying to avoid words like "cannot", "failed" in our error messages. Maybe:
```suggestion
		return "", fmt.Errorf("invalid ARN resource format %s", parsedArn.Resource)
```

Comment (efekarakus) [reply internal/pkg/describe/env.go:125]: Can we also add a comment with what the ARN looks like so that a reader can understand why this would be invalid?

File: internal/pkg/describe/env.go [hunk 27]
```diff
@@ -93,5 +153,20 @@ func (e *EnvDescription) HumanString() string {
 		fmt.Fprintf(writer, "  %s\t%s\n", app.Name, app.Type)
 	}
 	writer.Flush()
+	if len(e.Tags) != 0 {
+		fmt.Fprintf(writer, color.Bold.Sprint("\nTags\n\n"))
+		writer.Flush()
+		fmt.Fprintf(writer, "  %s\t%s\n", "Key", "Value")
+		// sort Tags in alpha order by keys
```
Comment (efekarakus) [inline internal/pkg/describe/env.go:160]: 👏

File: internal/pkg/describe/env.go (hunk 25 above)
Comment (efekarakus) [reply internal/pkg/describe/env.go:101]: Oh nvm! I see now :D looks good

File: internal/pkg/describe/env.go (hunk 24 above)
Comment (huanjani) [reply internal/pkg/describe/env.go:105]: Ahh, that makes sense. Thanks. Will adjust tests accordingly, too.
