### PR TITLE
fix(logs): change default logs retention time to 30 days

### LINKED ISSUE #651: Expose Log Retention in Manifest and/or update it to not be forever in Environments
Right now we set the log retention to be forever. This is not good, and is pretty unreasonable.

I think we can update the log groups to have a default retention and then perhaps let customers override it in their manifests.

Just ball parking, but I'm thinking non-prod environments ~ 1 month, prod environments ~3 months?

### PR DESCRIPTION
**Pull request by iamhopaul123**
fix #651. Updated to 30 days by default but not expose it to users to configure. Will be addressing in the future.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: internal/pkg/manifest/lb_fargate_manifest.go [hunk 1]
```diff
@@ -44,6 +45,11 @@ type ContainersConfig struct {
 	Secrets   map[string]string `yaml:"secrets"`
 }
 
+// LogsConfig is the configuration to the ECS logs.
+type LogsConfig struct {
+	LogRetention int `yaml:"logRetention"`
```
Comment (efekarakus) [inline internal/pkg/manifest/lb_fargate_manifest.go]: nit: I might be wrong, but I think you can write `time.Duration` here instead.
This way the constant can be written as:
```go
logRetentionDuration = 30 * 24 * time.Hour 
```

Comment (iamhopaul123) [reply internal/pkg/manifest/lb_fargate_manifest.go]: I don't think we need this...because the cloudformation just support values all in days and also for now we just want to do it simple and this pattern will be changed in the future. In this PR we want to change the default value from `infinity` to `30 days`.

When we expose this field then we will make it to be sth like `15d`, `1m` or so, then probably we can make use of `duration`. What do you think?
