### PR TITLE
fix(docker): docker build failed when multiple Dockerfile in one dir

### LINKED ISSUE #979: Only accepts dockerfile named Dockerfile
## Current Behavior
If I name my dockerfile something other than 'Dockerfile' (say 'db.Dockerfile'), during `app deploy` it will give me this error: _"unable to prepare context: context must be a directory"_. 

```bash
$ ecs-preview app init --dockerfile "db.Dockerfile"
$ ecs-preview app deploy # throws error
```

## Expected Behavior
Not throwing this error

### PR DESCRIPTION
**Pull request by iamhopaul123**
Fix #979

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: internal/pkg/docker/docker.go [hunk 1]
```diff
@@ -21,6 +26,23 @@ type runner interface {
 	Run(name string, args []string, options ...command.Option) error
 }
 
+// FilePath is the path of a Dockerfile.
+type FilePath string
+
+// parse returns the Dockerfile name and the path where Dockerfile resides.
+// Example: ./feDockerfile returns feDockerfile and .
+func (f FilePath) parse() (string, string) {
```
Comment (kohidave) [inline internal/pkg/docker/docker.go:34]: Have you considered using [this](https://golang.org/pkg/path/filepath/#Split)?

Comment (iamhopaul123) [reply internal/pkg/docker/docker.go:34]: This is awesome!

File: internal/pkg/docker/docker.go [hunk 2]
```diff
@@ -6,33 +6,35 @@ package docker
...
 	"strings"
 
 	"github.com/aws/amazon-ecs-cli-v2/internal/pkg/term/command"
 	"github.com/aws/amazon-ecs-cli-v2/internal/pkg/term/log"
 )
 
-// Service wraps a runner.
-type Service struct {
-	runner runner
+// Runner wraps a runner.
```
Comment (efekarakus) [inline internal/pkg/docker/docker.go:16]: nit: since `runner` is a private interface what do you think if we write:
```suggestion
// Runner represents a command that can be run.
```

File: internal/pkg/docker/docker.go [hunk 3]
```diff
@@ -6,33 +6,35 @@ package docker
...
 }
 
 // Build will run a `docker build` command with the input uri, tag, and Dockerfile image path.
-func (s Service) Build(uri, imageTag, path string) error {
+func (r Runner) Build(uri, imageTag, path string) error {
 	imageName := imageName(uri, imageTag)
+	dfPath, dfName := filepath.Split(path)
 
-	err := s.runner.Run("docker", []string{"build", "-t", imageName, path})
+	err := r.Run("docker", []string{"build", "-t", imageName, dfPath, "-f", dfName})
```
Comment (efekarakus) [inline internal/pkg/docker/docker.go:37]: awesome tyty 🙏
